// RUN: %ecoc %s -emit=jit 2>&1 | %FileCheck %s
//
// Test basic Maybe Just/Nothing case pattern.
// This tests the canonical case expression pattern generated by Elm.

module {
  // Helper function: case on Maybe, return inner value or default
  func.func private @extract_maybe(%maybe: !eco.value, %default: !eco.value) -> !eco.value {
    %result = eco.case %maybe : !eco.value [0, 1] -> (!eco.value) {case_kind = "ctor"} {
      // Nothing case: return default
      eco.yield %default : !eco.value
    }, {
      // Just case: extract and return the value
      %inner = eco.project.custom %maybe[0] : !eco.value -> !eco.value
      eco.yield %inner : !eco.value
    }
    return %result : !eco.value
  }

  func.func @main() -> i64 {
    %c0 = arith.constant 0 : i64
    %c42 = arith.constant 42 : i64
    %c99 = arith.constant 99 : i64

    // Create Maybe.Just 42
    %b42 = eco.box %c42 : i64 -> !eco.value
    %just = eco.construct.custom(%b42) {slot_kinds = array<i8: 0>, tag = 1 : i64, size = 1 : i64} : (!eco.value) -> !eco.value

    // Create the nullary ctor (tag 0) — an embedded null-cons constant
    // (HEAP_044); eco.construct.custom with size 0 is a verifier error.
    // (Real Maybe.Nothing compiles to the merged empty 0x6 with the
    // CONSTANT_TAG branch; this fixture pins the general nullary-ctor
    // dispatch path through the same eco.case.)
    %nothing = eco.constant.null_cons 0 : !eco.value

    // Default value
    %b99 = eco.box %c99 : i64 -> !eco.value

    // Test 1: Case on Just - should take tag 1 branch and return inner value (42)
    %result1 = func.call @extract_maybe(%just, %b99) : (!eco.value, !eco.value) -> !eco.value
    eco.dbg %result1 : !eco.value
    // CHECK: 42

    // Test 2: Case on Nothing - should take tag 0 branch and return default (99)
    %result2 = func.call @extract_maybe(%nothing, %b99) : (!eco.value, !eco.value) -> !eco.value
    eco.dbg %result2 : !eco.value
    // CHECK: 99

    return %c0 : i64
  }
}
