#!/usr/bin/env python3
"""Generates the Phase 3D limit fixtures (plans/wide-object-tail-kind-words-phase-3.md 3D.1):
construct_custom_2040.mlir, construct_record_2047.mlir (the widest legal objects, JIT run across
forced GCs) and construct_custom_2041_rejected.mlir, construct_record_2048_rejected.mlir (one past
the HEAP_019 limits). Run from test/codegen: python3 gen_wide_limit_fixtures.py"""

TY = {0: "i64", 1: "!eco.value", 2: "f64"}      # by k % 3
KIND = {0: 1, 1: 0, 2: 2}                         # slot kind by k % 3


def fields(n):
    lines, ops, tys, kinds = [], [], [], []
    lines.append("    %empty = eco.constant Empty : !eco.value")
    for k in range(n):
        r = k % 3
        if r == 0:
            lines.append(f"    %v{k} = arith.constant {k} : i64")
            ops.append(f"%v{k}")
        elif r == 1:
            ops.append("%empty")
        else:
            lines.append(f"    %v{k} = arith.constant {k}.5 : f64")
            ops.append(f"%v{k}")
        tys.append(TY[r])
        kinds.append(KIND[r])
    return lines, ops, tys, kinds


def construct(kind, n, ops, tys, kinds):
    sk = "array<i8: " + ", ".join(map(str, kinds)) + ">"
    if kind == "custom":
        attrs = f"{{tag = 4 : i64, size = {n} : i64, slot_kinds = {sk}}}"
        return f"    %obj = eco.construct.custom({', '.join(ops)}) {attrs} : ({', '.join(tys)}) -> !eco.value"
    attrs = f"{{field_count = {n} : i64, slot_kinds = {sk}}}"
    return f"    %obj = eco.construct.record({', '.join(ops)}) {attrs} : ({', '.join(tys)}) -> !eco.value"


def expected(k):
    r = k % 3
    return str(k) if r == 0 else ("<empty>" if r == 1 else f"{k}.5")


def positive(kind, n, probes):
    lines, ops, tys, kinds = fields(n)
    L = ["// RUN: %ecoc %s -emit=jit 2>&1 | %FileCheck %s", "//",
         f"// Phase 3D (plans/wide-object-tail-kind-words-phase-3.md 3D.1): the widest legal {kind}",
         f"// ({n} fields, HEAP_019), kinds Int/boxed/Float by k % 3, about 16 KiB: a large object on the",
         "// call path. Built, kept live across forced minor + major GCs, printed, then projected.",
         "// Generated by gen_wide_limit_fixtures.py.", "",
         "module {", "  llvm.func @eco_minor_gc()", "  llvm.func @eco_major_gc()", "",
         "  func.func @main() -> i64 {"]
    L += lines
    L.append(construct(kind, n, ops, tys, kinds))
    L += ["    llvm.call @eco_minor_gc() : () -> ()", "    llvm.call @eco_minor_gc() : () -> ()",
          "    llvm.call @eco_major_gc() : () -> ()", "    eco.dbg %obj : !eco.value"]
    checks = ["// CHECK: [eco.dbg] " + ("Ctor4 0 <empty> 2.5" if kind == "custom" else "{ f0 = 0, f1 = <empty>, f2 = 2.5")]
    for k in probes:
        t = TY[k % 3]
        L.append(f"    %p{k} = eco.project.{kind} %obj[{k}] : !eco.value -> {t}")
        L.append(f"    eco.dbg %p{k} : {t}")
        checks.append(f"// CHECK-NEXT: [eco.dbg] {expected(k)}")
    L += ["    %z = arith.constant 0 : i64", "    return %z : i64", "  }", "}", ""] + checks
    return "\n".join(L) + "\n"


def negative(kind, n, msg):
    lines, ops, tys, kinds = fields(n)
    L = ["// RUN: not %ecoc %s -emit=mlir 2>&1 | %FileCheck %s", "//",
         f"// Phase 3D (3D.1): one field past the HEAP_019 {kind} limit is rejected by the verifier.",
         "// Generated by gen_wide_limit_fixtures.py.", "",
         "module {", "  func.func @main() -> !eco.value {"]
    L += lines
    L.append(construct(kind, n, ops, tys, kinds))
    L += ["    return %obj : !eco.value", "  }", "}", "", f"// CHECK: {msg}"]
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    open("construct_custom_2040.mlir", "w").write(positive("custom", 2040, [23, 24, 55, 2039]))
    open("construct_record_2047.mlir", "w").write(positive("record", 2047, [31, 32, 63, 2046]))
    open("construct_custom_2041_rejected.mlir", "w").write(
        negative("custom", 2041, "size (2041) exceeds Custom's 2040-field limit"))
    open("construct_record_2048_rejected.mlir", "w").write(
        negative("record", 2048, "field_count (2048) exceeds Record's 2047-field limit"))
