// RUN: not %ecoc %s -emit=mlir 2>&1 | %FileCheck %s
//
// Phase 0 negative test: eco.to_heap rejects !eco.closure_env operands.
// Closure realisation must go through eco.make.closure (Q-A, CGEN_029).

module {
  func.func @bad_to_heap_closure_env(%a: i64, %b: !eco.value) -> !eco.value {
    %env = eco.make.closure_env(%a, %b)
         : (i64, !eco.value) -> !eco.closure_env<i64, !eco.value>
    %h = eco.to_heap %env : (!eco.closure_env<i64, !eco.value>) -> !eco.value
    return %h : !eco.value
  }
}

// The TableGen Eco_DataAggregate constraint catches this at the operand
// type check. The diagnostic is generated by the auto-generated verifier
// using the constraint's summary string.
// CHECK: must be eco data aggregate
