// RUN: %ecoc %s -emit=llvm 2>&1 | %FileCheck %s
//
// Phase D static-IR enforcement (CGEN_059 / CGEN_060):
// lowerGenericApply must not introduce eco_alloc_int/_float/_char calls
// to box primitive newargs before eco_apply_closure_eval. The runtime
// helper centralises any required re-boxing; the JIT'd IR must stay clean.

module {
  // Closure target: identity-style stub. Signature ptr(ptr) matches the
  // wrapper convention generated by getOrCreateWrapper. Body returns a
  // null HPtr — we only care about IR shape, not runtime behaviour.
  llvm.func @identity_eval(%args: !llvm.ptr) -> !llvm.ptr<1> {
    %z = llvm.mlir.constant(0 : i64) : i64
    %z_ptr = llvm.inttoptr %z : i64 to !llvm.ptr<1>
    llvm.return %z_ptr : !llvm.ptr<1>
  }

  func.func @main() -> i64 {
    %i = arith.constant 42 : i64

    // arity-1 closure, no captures.
    %pap0 = "eco.papCreate"() {
      function = @identity_eval,
      arity = 1 : i64,
      num_captured = 0 : i64
    } : () -> !eco.value

    // Generic apply (no remaining_arity attr) with a primitive (i64) newarg.
    // The lowering must produce a typed args buffer + EvalParamLayout +
    // call @eco_apply_closure_eval, with no eco_alloc_* call before it.
    %result = "eco.papExtend"(%pap0, %i) {
      newargs_unboxed_bitmap = 1 : i64
    } : (!eco.value, i64) -> !eco.value

    %zero = arith.constant 0 : i64
    return %zero : i64
  }
}

// Lowering ran — typed-apply runtime helper must appear in the IR.
// CHECK: eco_apply_closure_eval

// Forbidden: any reference to the primitive-boxing helpers. They should
// neither be called nor declared in this module — lowerGenericApply
// must not invoke getOrCreateAllocInt/Float/Char on this path.
// CHECK-NOT: @eco_alloc_int
// CHECK-NOT: @eco_alloc_float
// CHECK-NOT: @eco_alloc_char
