module SocketTlsHelp exposing
    ( server, trusted, listenTls, connectTls, connectOptions
    , tryCase, failure, alpnString
    )

{-| Shared helpers for the TLS tests (not a test: no `main`; plans/eco-system-sockets.md §4 S5).
The certificates come from `TlsFixtures` (generated by `scripts/gen-tls-fixtures.sh`).
-}

import Socket
import Socket.Address as Address exposing (Family(..))
import Socket.Tcp
import Socket.Tls
import SocketTestHelp as H
import Task exposing (Task)
import TlsFixtures as Fx


{-| Server options with the CA-signed certificate for `localhost` / `127.0.0.1`.
-}
server : List String -> Socket.Tls.ServerOptions
server alpn =
    { certificateChain = Fx.serverCertPem, privateKey = Fx.serverKeyPem, alpn = alpn }


{-| Client options trusting only the test CA.
-}
trusted : String -> List String -> Socket.Tls.ClientOptions
trusted serverName alpn =
    { serverName = serverName, verification = Socket.Tls.TrustedCertificates Fx.caPem, alpn = alpn }


{-| A TLS listener on 127.0.0.1 with a port picked by the system.
-}
listenTls : Socket.Tls.ServerOptions -> Task Socket.Error Socket.Listener
listenTls options =
    Socket.Tls.listen options (Socket.Tcp.defaultListenOptions (Address.loopback IPv4) 0)


connectOptions : Socket.Listener -> Socket.Tcp.ConnectOptions
connectOptions listener =
    Socket.Tcp.defaultConnectOptions (Address.loopback IPv4) (H.portOf listener)


connectTls : Socket.Tls.ClientOptions -> Socket.Listener -> Task Socket.Error Socket.Connection
connectTls options listener =
    Socket.Tls.connect options (connectOptions listener)


alpnString : Maybe String -> String
alpnString alpn =
    Maybe.withDefault "none" alpn


{-| `err <code> certificate-invalid <Bool>`.
-}
failure : Socket.Error -> String
failure e =
    "err " ++ Socket.errorCode e ++ " certificate-invalid " ++ H.boolString (Socket.errorIsCertificateInvalid e)


{-| One handshake against a fresh listener: `ok alpn <protocol or none>` (both ends then closed),
or the client's `failure`. A server whose handshake fails drops the connection silently, so its
parked `accept` is cancelled by `closeListener`. The listener is closed in both cases.
-}
tryCase : Socket.Tls.ServerOptions -> Socket.Tls.ClientOptions -> Task String String
tryCase serverOptions clientOptions =
    H.socketErr (listenTls serverOptions)
        |> Task.andThen
            (\listener ->
                H.async (H.socketErr (Socket.accept listener))
                    |> Task.andThen
                        (\accepted ->
                            connectTls clientOptions listener
                                |> Task.andThen (\conn -> Socket.Tls.info conn |> Task.map (\info -> ( conn, info )))
                                |> Task.map Ok
                                |> Task.onError (\e -> Task.succeed (Err e))
                                |> Task.andThen
                                    (\result ->
                                        case result of
                                            Ok ( conn, info ) ->
                                                Socket.close conn
                                                    |> Task.andThen (\_ -> accepted)
                                                    |> Task.andThen Socket.close
                                                    |> Task.map (\_ -> "ok alpn " ++ alpnString info.alpn)

                                            Err e ->
                                                Task.succeed (failure e)
                                    )
                                |> Task.andThen
                                    (\line ->
                                        H.socketErr (Socket.closeListener listener)
                                            |> Task.map (\_ -> line)
                                    )
                        )
            )
