//===- eco-boot.cpp - Eco native compiler driver --------------------------===//
//
// Compiles Elm source files (or .mlir files) to standalone x86-64 Linux ELF
// executables. Orchestrates:
//   1. Elm frontend (Node.js eco-boot-2-runner.js) to produce .mlir
//   2. MLIR lowering pipeline (Eco dialect -> LLVM dialect)
//   3. Translation to LLVM IR
//   4. Object file emission via TargetMachine
//   5. Linking via clang++ driver with runtime/kernel static libraries
//
// A .o input short-circuits the pipeline straight to step 5, so an unchanged
// .mlir can be re-linked against freshly-rebuilt runtime/kernel libraries
// without re-running the heavy MLIR/LLVM lowering. Used by the C++-only
// edit-test loop in heap-profile.py.
//
// Usage: eco-boot <input.elm|input.mlir|input.o> [options]
//
//===----------------------------------------------------------------------===//

#include <cassert>
#include <cstring>
#include <algorithm>
#include <thread>
#include <vector>

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#endif

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlow.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/Extensions/AllExtensions.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/Transforms/InlinerInterfaceImpl.h"
#include "mlir/Dialect/SCF/IR/SCF.h"

#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVMPass.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Conversion/SCFToControlFlow/SCFToControlFlow.h"
#include "mlir/Conversion/ReconcileUnrealizedCasts/ReconcileUnrealizedCasts.h"

#include "mlir/ExecutionEngine/OptUtils.h"

#include "mlir/IR/AsmState.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/OwningOpRef.h"
#include "mlir/IR/Verifier.h"

#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"

#include "mlir/Support/FileUtilities.h"

#include "mlir/Target/LLVMIR/Dialect/Builtin/BuiltinToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Export.h"

#include "mlir/Transforms/Passes.h"

#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Support/SourceMgr.h"

#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/SubtargetFeature.h"

#include "EcoDialect.h"
#include "EcoOps.h"
#include "Passes.h"
#include "EcoBackend.h"
#include "EcoPipeline.h"
#include "LoweringStats.h"

#include "llvm/Analysis/TargetLibraryInfo.h"

namespace eco { void linkEcoGCStrategy(); }
static struct EcoGCStrategyLinker {
    EcoGCStrategyLinker() { eco::linkEcoGCStrategy(); }
} ecoGCStrategyLinker;

// Generated by CMake with absolute paths to static libraries
#include "eco/EcoBootConfig.h"

using namespace mlir;

namespace cl = llvm::cl;

//===----------------------------------------------------------------------===//
// Command Line Options
//===----------------------------------------------------------------------===//

static cl::opt<std::string> inputFilename(
    cl::Positional,
    cl::desc("<input .elm, .mlir, or .o file>"),
    cl::Required);

static cl::opt<std::string> outputFilename(
    "o",
    cl::desc("Output path (default: a.out for exe, <input>.o for obj)"),
    cl::value_desc("filename"),
    cl::init(""));

namespace {
enum Action {
    EmitExe,
    EmitObj,
    EmitLLVM,
    EmitMLIR
};
} // namespace

static cl::opt<enum Action> emitAction(
    "emit",
    cl::desc("Select the kind of output desired"),
    cl::values(
        clEnumValN(EmitExe, "exe", "Emit linked ELF executable (default)"),
        clEnumValN(EmitObj, "obj", "Emit object file only"),
        clEnumValN(EmitLLVM, "llvm", "Emit LLVM IR"),
        clEnumValN(EmitMLIR, "mlir", "Emit MLIR (frontend only)")),
    cl::init(EmitExe));

static cl::opt<unsigned> optLevel(
    "O",
    cl::desc("Optimization level (0-3)"),
    cl::value_desc("level"),
    cl::init(2));

static cl::opt<std::string> frontendRunner(
    "frontend",
    cl::desc("Path to Node.js runner script (eco-boot-2-runner.js)"),
    cl::value_desc("path"),
    cl::init(""));

static cl::opt<std::string> workDir(
    "workdir",
    cl::desc("Working directory for frontend (auto-detected from elm.json if omitted)"),
    cl::value_desc("path"),
    cl::init(""));

static cl::opt<bool> verbose(
    "verbose",
    cl::desc("Print subcommands being executed"),
    cl::init(false));

static cl::opt<bool> gcSections(
    "gc-sections",
    cl::desc("Link with --gc-sections (+ .llvm_stackmaps KEEP) to strip dead "
             "sections. Binary-size only; opt-in until broadly validated"),
    cl::init(false));

static cl::opt<unsigned> splitCodegen(
    "split-codegen",
    cl::desc("Parallel object emission: split the optimized module into N "
             "partitions emitted concurrently (executable output only). "
             "0 = auto (cores), 1 = off"),
    cl::init(0));

static cl::opt<bool> rs4gcAfterOpt(
    "rs4gc-after-opt",
    cl::desc("EXPERIMENTAL: run RewriteStatepointsForGC after the O2 pipeline "
             "instead of before (faster opt, but risks REP_LLVM_001(a)). "
             "Off by default; needs GC-stress validation before default use"),
    cl::init(false));

static cl::opt<std::string> dumpRS4GCIR(
    "dump-rs4gc-ir",
    cl::desc("Dump LLVM IR to file after RS4GC pass (for GC diagnostics)"),
    cl::value_desc("filename"),
    cl::init(""));

static cl::opt<std::string> dumpPreRS4GCIR(
    "dump-pre-rs4gc-ir",
    cl::desc("Dump LLVM IR to file before RS4GC pass (for GC diagnostics)"),
    cl::value_desc("filename"),
    cl::init(""));

static cl::opt<bool> printStats(
    "lowering-stats",
    cl::desc("Print lowering-pipeline timing breakdown to stderr at exit"),
    cl::init(true));

//===----------------------------------------------------------------------===//
// Frontend Invocation
//===----------------------------------------------------------------------===//

static bool isElmFile(llvm::StringRef path) {
    return path.ends_with(".elm");
}

static bool isMlirFile(llvm::StringRef path) {
    return path.ends_with(".mlir");
}

static bool isObjectFile(llvm::StringRef path) {
    return path.ends_with(".o");
}

/// Walk up from `startPath` looking for a directory containing elm.json.
static std::string findElmProjectRoot(const std::string &startPath) {
    llvm::SmallString<256> dir(startPath);
    llvm::sys::path::remove_filename(dir); // start from file's parent

    while (!dir.empty()) {
        llvm::SmallString<256> candidate(dir);
        llvm::sys::path::append(candidate, "elm.json");
        if (llvm::sys::fs::exists(candidate))
            return std::string(dir);

        // parent_path returns a StringRef into dir's buffer, so copy it
        // to a temporary before reassigning.
        std::string parent(llvm::sys::path::parent_path(dir));
        if (parent == std::string(dir))
            break; // reached filesystem root
        dir = parent;
    }
    return "";
}

static int compileElmToMlir(const std::string &elmFile,
                             const std::string &mlirOutput) {
    if (frontendRunner.empty()) {
        llvm::errs() << "Error: --frontend=<path> is required for .elm input\n";
        return 1;
    }

    auto nodeOrErr = llvm::sys::findProgramByName("node");
    if (!nodeOrErr) {
        llvm::errs() << "Error: 'node' not found in PATH\n";
        return 1;
    }

    // Determine the Elm project directory (must contain elm.json).
    std::string projectDir = workDir;
    if (projectDir.empty())
        projectDir = findElmProjectRoot(elmFile);
    if (projectDir.empty()) {
        llvm::errs() << "Error: Could not find elm.json for '" << elmFile
                     << "'. Use --workdir=<dir> to specify the project root.\n";
        return 1;
    }

    // Make elmFile and mlirOutput absolute before changing cwd.
    llvm::SmallString<256> absElm(elmFile);
    llvm::sys::fs::make_absolute(absElm);
    llvm::SmallString<256> absOutput(mlirOutput);
    llvm::sys::fs::make_absolute(absOutput);

    std::string outputArg = "--output=" + std::string(absOutput);

    llvm::SmallVector<llvm::StringRef> args;
    args.push_back(*nodeOrErr);
    args.push_back(frontendRunner);
    args.push_back("make");
    args.push_back(outputArg);
    args.push_back(llvm::StringRef(absElm));

    if (verbose) {
        llvm::errs() << "[eco-boot] frontend (cwd=" << projectDir << "):";
        for (auto &a : args)
            llvm::errs() << " " << a;
        llvm::errs() << "\n";
    }

    // Save current directory, cd to project root, invoke frontend, restore.
    llvm::SmallString<256> savedCwd;
    llvm::sys::fs::current_path(savedCwd);
    if (auto ec = llvm::sys::fs::set_current_path(projectDir)) {
        llvm::errs() << "Error: Could not change to directory '"
                     << projectDir << "': " << ec.message() << "\n";
        return 1;
    }

    std::string errMsg;
    int rc = llvm::sys::ExecuteAndWait(
        *nodeOrErr, args, /*env=*/std::nullopt,
        /*redirects=*/{}, /*secondsToWait=*/0, /*memoryLimit=*/0, &errMsg);

    // Restore original working directory.
    llvm::sys::fs::set_current_path(savedCwd);

    if (rc != 0) {
        llvm::errs() << "Error: frontend compilation failed";
        if (!errMsg.empty())
            llvm::errs() << ": " << errMsg;
        llvm::errs() << "\n";
        return 1;
    }
    return 0;
}

//===----------------------------------------------------------------------===//
// MLIR Loading and Pipeline
//===----------------------------------------------------------------------===//

static OwningOpRef<ModuleOp> loadMLIR(MLIRContext &context,
                                       llvm::SourceMgr &sourceMgr) {
    auto module = parseSourceFile<ModuleOp>(sourceMgr, &context);
    if (!module)
        llvm::errs() << "Error: Failed to parse MLIR file\n";
    return module;
}

static int runPipeline(ModuleOp module, eco::LoweringStats &stats) {
    PassManager pm(module->getName());

    if (failed(applyPassManagerCLOptions(pm)))
        return 1;

#ifndef ECO_LOWERING_VALIDATION
    // Release builds: skip the after-each-pass full-module verifier. The
    // parser already verified the input and the lowering passes are covered
    // by the test suite; a full verify after each of ~13 top-level passes is
    // O(module) each and pure overhead here. Validation builds keep it on to
    // localise any pass that emits invalid IR.
    pm.enableVerifier(false);
#endif

    // Per-pass timing — installed before passes are added so every pass
    // (including ones registered by buildEcoToLLVMPipeline) is observed.
    pm.addInstrumentation(stats.makePassInstrumentation());

    eco::EcoPipelineOptions pipeOpts;
    eco::buildEcoToLLVMPipeline(pm, pipeOpts);

    if (failed(pm.run(module)))
        return 1;

    return 0;
}

//===----------------------------------------------------------------------===//
// LLVM IR Translation
//===----------------------------------------------------------------------===//

static std::unique_ptr<llvm::Module> translateToLLVMIR(
    ModuleOp module, llvm::LLVMContext &llvmContext) {
    registerBuiltinDialectTranslation(*module->getContext());
    registerLLVMDialectTranslation(*module->getContext());

    auto llvmModule = translateModuleToLLVMIR(module, llvmContext);
    if (!llvmModule) {
        llvm::errs() << "Error: Failed to translate MLIR to LLVM IR\n";
        return nullptr;
    }

    // Rename "main" to "eco_main" to avoid conflict with C main()
    // in the entry wrapper.
    if (auto *mainFn = llvmModule->getFunction("main")) {
        mainFn->setName("eco_main");
    }

    return llvmModule;
}

//===----------------------------------------------------------------------===//
// Target Machine Creation
//
// The target CPU/feature pin and TargetMachine factory live in EcoBackend.h
// (createEcoTargetMachine / kEcoTargetCPU), shared with EcoNativeDriver.cpp.
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// Object File Emission
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
// Linking — delegates to EcoNativeDriverStatic, which invokes the system
// linker (ld.bfd) directly. The previous clang++ driver invocation is gone;
// see EcoNativeDriver.cpp::linkExecutable for the full link line.
//===----------------------------------------------------------------------===//

#include "EcoNativeDriver.h"

static bool outputIsSharedLib(const std::string &outputPath) {
    auto endsWith = [&](const char *suffix) {
        size_t n = std::strlen(suffix);
        return outputPath.size() >= n &&
               outputPath.compare(outputPath.size() - n, n, suffix) == 0;
    };
    return endsWith(".so") || endsWith(".node");
}

static int linkExecutable(const std::string &objectFile,
                          const std::string &outputPath) {
    eco::EcoNativeOptions opts;
    opts.verbose = verbose;
    opts.gcSections = gcSections;
    // .so/.node output targets link as shared libraries with the
    // host-embedding entry (see plans/native-ports-and-embedding.md).
    return eco::linkExecutable(objectFile, outputPath, opts,
                               outputIsSharedLib(outputPath));
}

static int linkExecutable(const std::vector<std::string> &objectFiles,
                          const std::string &outputPath) {
    eco::EcoNativeOptions opts;
    opts.verbose = verbose;
    opts.gcSections = gcSections;
    return eco::linkExecutable(objectFiles, outputPath, opts,
                               outputIsSharedLib(outputPath));
}

//===----------------------------------------------------------------------===//
// Output Path Logic
//===----------------------------------------------------------------------===//

static std::string getOutputPath() {
    if (!outputFilename.empty())
        return outputFilename;

    switch (emitAction) {
    case EmitExe:
        return "a.out";
    case EmitObj: {
        llvm::SmallString<256> path(inputFilename.getValue());
        llvm::sys::path::replace_extension(path, ".o");
        return std::string(path);
    }
    case EmitLLVM: {
        llvm::SmallString<256> path(inputFilename.getValue());
        llvm::sys::path::replace_extension(path, ".ll");
        return std::string(path);
    }
    case EmitMLIR:
        return "-"; // stdout
    }
    return "a.out";
}

//===----------------------------------------------------------------------===//
// Main
//===----------------------------------------------------------------------===//

// Win64 teardown hard-exit. eco-boot-native links all of LLVM/MLIR; returning
// from main runs the /MT CRT exit() -> ExitProcess, whose DLL_PROCESS_DETACH +
// static-destructor sweep intermittently stalls at process teardown. The
// lowering, the linked output binary and the stats are all complete by this
// point, so exit immediately as POSIX effectively does. TerminateProcess
// (unlike ExitProcess) skips DLL detach entirely, so it cannot wedge on a
// teardown lock. No-op on POSIX — the caller's `return` runs normally.
static void ecoBootFinalExit(int rc) {
#if defined(_WIN32)
    llvm::outs().flush();
    llvm::errs().flush();
    ::TerminateProcess(::GetCurrentProcess(), static_cast<UINT>(rc));
    // TerminateProcess is asynchronous; if it ever returns, do NOT fall through
    // to the CRT teardown — spin until the OS process rundown reaps us.
    for (;;) { ::Sleep(1000); }
#else
    (void)rc;
#endif
}

int main(int argc, char **argv) {
    llvm::InitLLVM initLLVM(argc, argv);

    // Initialize LLVM native target for object emission.
    llvm::InitializeNativeTarget();
    llvm::InitializeNativeTargetAsmPrinter();
    llvm::InitializeNativeTargetAsmParser();

    registerAsmPrinterCLOptions();
    registerMLIRContextCLOptions();
    registerPassManagerCLOptions();

    cl::ParseCommandLineOptions(argc, argv,
        "Eco native compiler\n\n"
        "Compiles Elm source files or MLIR to native x86-64 Linux executables.\n");

    std::string output = getOutputPath();

    // Lifetime spans the whole driver — phases below add to it via Scope, and
    // we print the aggregated table just before main() returns.
    eco::LoweringStats stats;

    // Fast path: when the input is an already-emitted object file, skip the
    // MLIR parse / lowering / LLVM-IR / RS4GC / object-emission pipeline and
    // go straight to the link step. This is the C++-only edit-test loop:
    // .mlir hasn't changed, only the runtime/kernel libraries have, so the
    // cached .o still reflects the current Elm-side compiler and only
    // re-linking is required.
    if (isObjectFile(inputFilename)) {
        if (emitAction != EmitExe) {
            llvm::errs()
                << "Error: when input is an object file, --emit must be 'exe' "
                << "(default); the MLIR/LLVM pipeline does not run for .o "
                << "input.\n";
            return 1;
        }
        int rc;
        {
            eco::LoweringStats::Scope scope(stats, "Link (clang++ driver)");
            rc = linkExecutable(inputFilename, output);
        }
        if (printStats) {
            stats.print(llvm::errs());
        }
        return rc;
    }

    // Step 1: Get MLIR input (either directly or via frontend compilation)
    std::string mlirFile;
    std::string tempMlirFile;

    if (isMlirFile(inputFilename)) {
        mlirFile = inputFilename;
    } else if (isElmFile(inputFilename)) {
        if (emitAction == EmitMLIR) {
            // Just run the frontend and output the MLIR
            std::string mlirOutput = (output == "-") ? "/dev/stdout" : output;
            int rc;
            {
                eco::LoweringStats::Scope scope(stats, "frontend (Elm -> MLIR)");
                rc = compileElmToMlir(inputFilename, mlirOutput);
            }
            if (printStats) {
                stats.print(llvm::errs());
            }
            return rc;
        }

        // Create a temp file for the MLIR intermediate
        llvm::SmallString<256> tempPath;
        if (auto ec = llvm::sys::fs::createTemporaryFile(
                "eco-boot", "mlir", tempPath)) {
            llvm::errs() << "Error: Could not create temp file: "
                         << ec.message() << "\n";
            return 1;
        }
        tempMlirFile = std::string(tempPath);
        mlirFile = tempMlirFile;

        {
            eco::LoweringStats::Scope scope(stats, "frontend (Elm -> MLIR)");
            if (compileElmToMlir(inputFilename, mlirFile) != 0) {
                llvm::sys::fs::remove(tempMlirFile);
                return 1;
            }
        }
    } else {
        llvm::errs()
            << "Error: Input file must be .elm, .mlir, or .o (re-link only)\n";
        return 1;
    }

    // Step 2: Parse MLIR
    DialectRegistry registry;
    eco::registerRequiredDialects(registry);

    MLIRContext context(registry);
#if defined(_WIN32)
    // Win64: run MLIR lowering single-threaded. MLIRContext's default ctor
    // spins up a per-context worker thread pool that parks for the context's
    // lifetime; the hard-exit (ecoBootFinalExit) already handles teardown, but
    // single-threading avoids leaving parked pool threads to be force-killed
    // and keeps lowering deterministic. The dominant cost (LLVM backend object
    // emission) is single-threaded regardless, so the wall-clock hit is small.
    context.disableMultithreading();
#endif
    eco::loadRequiredDialects(context);
    context.allowUnregisteredDialects();

    std::string errorMessage;
    auto inputFile = openInputFile(mlirFile, &errorMessage);
    if (!inputFile) {
        llvm::errs() << "Error: " << errorMessage << "\n";
        if (!tempMlirFile.empty())
            llvm::sys::fs::remove(tempMlirFile);
        return 1;
    }

    llvm::SourceMgr sourceMgr;
    sourceMgr.AddNewSourceBuffer(std::move(inputFile), llvm::SMLoc());

    OwningOpRef<ModuleOp> module;
    {
        eco::LoweringStats::Scope scope(stats, "MLIR parse + verify");
        module = loadMLIR(context, sourceMgr);
        if (!module) {
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }

#ifdef ECO_LOWERING_VALIDATION
        // Redundant in release: parseSourceFile already verifies the parsed
        // module. Kept only in validation builds as a belt-and-braces check.
        if (failed(verify(*module))) {
            llvm::errs() << "Error: Module verification failed\n";
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }
#endif
    }

    // Step 3: Run MLIR lowering pipeline (Eco -> LLVM dialect)
    {
        eco::LoweringStats::Scope scope(stats, "MLIR lowering pipeline");
        if (runPipeline(*module, stats) != 0) {
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }
    }

    // Step 4: Translate to LLVM IR
    llvm::LLVMContext llvmContext;
    std::unique_ptr<llvm::Module> llvmModule;
    {
        eco::LoweringStats::Scope scope(stats, "MLIR -> LLVM IR translation");
        llvmModule = translateToLLVMIR(*module, llvmContext);
        if (!llvmModule) {
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }
    }

    // Step 5: Create TargetMachine and set DataLayout BEFORE RS4GC (Phase 3
    // of the pipeline-convergence plan — matches the JIT path's ordering).
    // createEcoTargetMachine() is opt-level aware; that is load-bearing for
    // AOT -O0..-O3 codegen.
    std::unique_ptr<llvm::TargetMachine> tm;
    {
        eco::LoweringStats::Scope scope(stats, "TargetMachine init");
        tm = eco::createEcoTargetMachine(*llvmModule, optLevel.getValue());
        if (!tm)
            return 1;
    }

    // Clean up temp MLIR file now that we're done with it.
    if (!tempMlirFile.empty())
        llvm::sys::fs::remove(tempMlirFile);

    // EmitLLVM is a text-dump path: RS4GC via runEcoBackend(DumpLLVMText), then
    // tool-side opt + IR print. Object emission stays out of this branch.
    if (emitAction == EmitLLVM) {
        {
            eco::LoweringStats::Scope scope(stats, "LLVM RS4GC pipeline");
            eco::EcoBackendJob job;
            job.kind = eco::BackendKind::DumpLLVMText;
            job.tm = tm.get();
            job.needsFramePointerAttr = true;
            job.preRS4GCDumpPath = dumpPreRS4GCIR;
            job.postRS4GCDumpPath = dumpRS4GCIR;
            if (auto err = eco::runEcoBackend(*llvmModule, job)) {
                llvm::errs() << "Error: RS4GC failed: " << err << "\n";
                return 1;
            }
        }
        if (optLevel > 0) {
            eco::LoweringStats::Scope scope(stats, "LLVM optimization (-O>0)");
            auto optPipeline = makeOptimizingTransformer(
                optLevel, /*sizeLevel=*/0, /*targetMachine=*/tm.get());
            if (auto err = optPipeline(llvmModule.get())) {
                llvm::errs() << "Error: LLVM optimization failed: " << err << "\n";
                return 1;
            }
        }
        {
            eco::LoweringStats::Scope scope(stats, "Emit LLVM IR");
            if (output == "-") {
                llvm::outs() << *llvmModule << "\n";
            } else {
                std::error_code ec;
                llvm::raw_fd_ostream out(output, ec, llvm::sys::fs::OF_None);
                if (ec) {
                    llvm::errs() << "Error: Could not open output file: "
                                 << ec.message() << "\n";
                    return 1;
                }
                out << *llvmModule << "\n";
            }
        }
        if (printStats) {
            stats.print(llvm::errs());
        }
        return 0;
    }

    // EmitObj / EmitExe: target an object file path; runEcoBackend drives the
    // full RS4GC + opt + object-emit sequence. Exe linking stays in this tool
    // because it depends on EcoBootConfig.h's deployment paths.
    std::string objFile;
    std::string tempObjFile;
    // `-o foo.o` with the default --emit=exe is object-only output too.
    bool emitObjOnly =
        (emitAction == EmitObj) ||
        (output.size() >= 2 &&
         output.compare(output.size() - 2, 2, ".o") == 0);
    if (emitObjOnly) {
        objFile = output;
    } else {
        llvm::SmallString<256> tempPath;
        if (auto ec = llvm::sys::fs::createTemporaryFile(
                "eco-boot", "o", tempPath)) {
            llvm::errs() << "Error: Could not create temp file: "
                         << ec.message() << "\n";
            return 1;
        }
        tempObjFile = std::string(tempPath);
        objFile = tempObjFile;
    }

    const bool isExecutable = !emitObjOnly && !outputIsSharedLib(output);

    // Executable output only: internalize all generated symbols except the two
    // the C entry lib resolves by name, then GlobalDCE the unreachable
    // remainder — before RS4GC/opt/codegen. Skipped for object-only output
    // (relinked later, must keep symbols visible) and shared libs (need
    // __eco_root_module / napi exports).
    if (isExecutable) {
        eco::LoweringStats::Scope scope(stats, "Internalize + GlobalDCE");
        eco::internalizeAndDCEForExecutable(*llvmModule);
    }

    // Parallel codegen: split the optimized module into N partitions emitted
    // concurrently (executable output only — internalize ran, so cross-
    // partition locals externalize with a single definition). 0 = auto.
    // Object emission dominates the AOT backend and is per-function work, so
    // splitting it across cores is a near-linear win on large programs. Small
    // modules are gated out — per-partition bitcode-serialize + thread + link
    // overhead would dominate when emission is already sub-second.
    unsigned numParts = 1;
    if (isExecutable && splitCodegen != 1) {
        unsigned numDefinedFns = 0;
        for (auto &F : *llvmModule)
            if (!F.isDeclaration())
                ++numDefinedFns;
        // Only split modules with enough functions to amortize the overhead.
        constexpr unsigned kMinFnsToSplit = 4000;
        if (numDefinedFns >= kMinFnsToSplit) {
            unsigned cores = std::max(1u, std::thread::hardware_concurrency());
            // Auto caps at 16: beyond that the serial split + per-partition
            // bitcode-serialize overhead outweighs the extra emission
            // parallelism (measured on the self-host module). An explicit
            // --split-codegen=N is honoured as-is.
            unsigned want =
                splitCodegen == 0 ? std::min(cores, 16u) : splitCodegen.getValue();
            // ~1 partition per 2000 functions, capped at the requested/core
            // count and never fewer than 2 once we've decided to split.
            unsigned bySize = std::max(2u, numDefinedFns / 2000u);
            numParts = std::min(want, bySize);
        }
    }
    std::vector<std::string> partObjFiles;
    if (numParts > 1) {
        for (unsigned i = 0; i < numParts; ++i) {
            llvm::SmallString<256> p;
            if (auto ec = llvm::sys::fs::createTemporaryFile("eco-boot-part",
                                                             "o", p)) {
                llvm::errs() << "Error: Could not create temp file: "
                             << ec.message() << "\n";
                for (auto &f : partObjFiles)
                    llvm::sys::fs::remove(f);
                return 1;
            }
            partObjFiles.emplace_back(p.str());
        }
    }

    {
        eco::LoweringStats::Scope scope(stats,
            "LLVM backend (RS4GC + opt + object emission)");
        eco::EcoBackendJob job;
        job.kind = eco::BackendKind::EmitObjectFile;
        job.tm = tm.get();
        job.optLevel = optLevel > 0
            ? static_cast<llvm::CodeGenOptLevel>(std::min(optLevel.getValue(), 3u))
            : llvm::CodeGenOptLevel::None;
        job.needsFramePointerAttr = true;
        job.preRS4GCDumpPath = dumpPreRS4GCIR;
        job.postRS4GCDumpPath = dumpRS4GCIR;
        job.rs4gcAfterOpt = rs4gcAfterOpt;
        if (numParts > 1) {
            job.numPartitions = numParts;
            job.objectFilePaths = partObjFiles;
        } else {
            job.objectFilePath = objFile;
        }
        if (auto err = eco::runEcoBackend(*llvmModule, job)) {
            llvm::errs() << "Error: backend pipeline failed: " << err << "\n";
            if (!tempObjFile.empty())
                llvm::sys::fs::remove(tempObjFile);
            for (auto &f : partObjFiles)
                llvm::sys::fs::remove(f);
            return 1;
        }
    }

    if (verbose)
        llvm::errs() << "[eco-boot] emitted object file(s): "
                     << (numParts > 1 ? std::to_string(numParts) + " partitions"
                                      : objFile)
                     << "\n";

    if (emitObjOnly) {
        if (printStats) {
            stats.print(llvm::errs());
        }
        ecoBootFinalExit(0);
        return 0;
    }

    // Step 8: Link executable
    int rc;
    {
        eco::LoweringStats::Scope scope(stats, "Link (clang++ driver)");
        rc = numParts > 1 ? linkExecutable(partObjFiles, output)
                          : linkExecutable(objFile, output);
    }

    // Clean up temp object file(s)
    if (!tempObjFile.empty())
        llvm::sys::fs::remove(tempObjFile);
    for (auto &f : partObjFiles)
        llvm::sys::fs::remove(f);

    if (printStats) {
        stats.print(llvm::errs());
    }

    ecoBootFinalExit(rc);
    return rc;
}
