//===- eco-boot.cpp - Eco native compiler driver --------------------------===//
//
// Compiles Elm source files (or .mlir files) to standalone x86-64 Linux ELF
// executables. Orchestrates:
//   1. Elm frontend (Node.js eco-boot-2-runner.js) to produce .mlir
//   2. MLIR lowering pipeline (Eco dialect -> LLVM dialect)
//   3. Translation to LLVM IR
//   4. Object file emission via TargetMachine
//   5. Linking via clang++ driver with runtime/kernel static libraries
//
// A .o input short-circuits the pipeline straight to step 5, so an unchanged
// .mlir can be re-linked against freshly-rebuilt runtime/kernel libraries
// without re-running the heavy MLIR/LLVM lowering. Used by the C++-only
// edit-test loop in heap-profile.py.
//
// Usage: eco-boot <input.elm|input.mlir|input.o> [options]
//
//===----------------------------------------------------------------------===//

#include <cassert>

#include "mlir/Dialect/Arith/IR/Arith.h"
#include "mlir/Dialect/ControlFlow/IR/ControlFlow.h"
#include "mlir/Dialect/Func/IR/FuncOps.h"
#include "mlir/Dialect/Func/Extensions/AllExtensions.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/Transforms/InlinerInterfaceImpl.h"
#include "mlir/Dialect/SCF/IR/SCF.h"

#include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
#include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
#include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVMPass.h"
#include "mlir/Conversion/LLVMCommon/ConversionTarget.h"
#include "mlir/Conversion/LLVMCommon/TypeConverter.h"
#include "mlir/Conversion/SCFToControlFlow/SCFToControlFlow.h"
#include "mlir/Conversion/ReconcileUnrealizedCasts/ReconcileUnrealizedCasts.h"

#include "mlir/ExecutionEngine/OptUtils.h"

#include "mlir/IR/AsmState.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/OwningOpRef.h"
#include "mlir/IR/Verifier.h"

#include "mlir/Parser/Parser.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"

#include "mlir/Support/FileUtilities.h"

#include "mlir/Target/LLVMIR/Dialect/Builtin/BuiltinToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
#include "mlir/Target/LLVMIR/Export.h"

#include "mlir/Transforms/Passes.h"

#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/SubtargetFeature.h"

#include "EcoDialect.h"
#include "EcoOps.h"
#include "Passes.h"
#include "EcoBackend.h"
#include "EcoPipeline.h"
#include "LoweringStats.h"

#include "llvm/Analysis/TargetLibraryInfo.h"

namespace eco { void linkEcoGCStrategy(); }
static struct EcoGCStrategyLinker {
    EcoGCStrategyLinker() { eco::linkEcoGCStrategy(); }
} ecoGCStrategyLinker;

// Generated by CMake with absolute paths to static libraries
#include "eco/EcoBootConfig.h"

using namespace mlir;

namespace cl = llvm::cl;

//===----------------------------------------------------------------------===//
// Command Line Options
//===----------------------------------------------------------------------===//

static cl::opt<std::string> inputFilename(
    cl::Positional,
    cl::desc("<input .elm, .mlir, or .o file>"),
    cl::Required);

static cl::opt<std::string> outputFilename(
    "o",
    cl::desc("Output path (default: a.out for exe, <input>.o for obj)"),
    cl::value_desc("filename"),
    cl::init(""));

namespace {
enum Action {
    EmitExe,
    EmitObj,
    EmitLLVM,
    EmitMLIR
};
} // namespace

static cl::opt<enum Action> emitAction(
    "emit",
    cl::desc("Select the kind of output desired"),
    cl::values(
        clEnumValN(EmitExe, "exe", "Emit linked ELF executable (default)"),
        clEnumValN(EmitObj, "obj", "Emit object file only"),
        clEnumValN(EmitLLVM, "llvm", "Emit LLVM IR"),
        clEnumValN(EmitMLIR, "mlir", "Emit MLIR (frontend only)")),
    cl::init(EmitExe));

static cl::opt<unsigned> optLevel(
    "O",
    cl::desc("Optimization level (0-3)"),
    cl::value_desc("level"),
    cl::init(2));

static cl::opt<std::string> frontendRunner(
    "frontend",
    cl::desc("Path to Node.js runner script (eco-boot-2-runner.js)"),
    cl::value_desc("path"),
    cl::init(""));

static cl::opt<std::string> workDir(
    "workdir",
    cl::desc("Working directory for frontend (auto-detected from elm.json if omitted)"),
    cl::value_desc("path"),
    cl::init(""));

static cl::opt<bool> verbose(
    "verbose",
    cl::desc("Print subcommands being executed"),
    cl::init(false));

static cl::opt<std::string> dumpRS4GCIR(
    "dump-rs4gc-ir",
    cl::desc("Dump LLVM IR to file after RS4GC pass (for GC diagnostics)"),
    cl::value_desc("filename"),
    cl::init(""));

static cl::opt<std::string> dumpPreRS4GCIR(
    "dump-pre-rs4gc-ir",
    cl::desc("Dump LLVM IR to file before RS4GC pass (for GC diagnostics)"),
    cl::value_desc("filename"),
    cl::init(""));

static cl::opt<bool> printStats(
    "lowering-stats",
    cl::desc("Print lowering-pipeline timing breakdown to stderr at exit"),
    cl::init(true));

static cl::opt<bool> enableUnboxedAgg(
    "enable-unboxed-agg",
    cl::desc("Enable Phase 1 escape analysis + Phase 2 specialise + "
             "Phase 3 cross-function specialise + Phase 3.1 flatten + "
             "Phase 3.2 SCC passes for value-level aggregates "
             "(on by default after Phase 3.2 landed; pass "
             "-enable-unboxed-agg=false to opt out)"),
    cl::init(true));

//===----------------------------------------------------------------------===//
// Frontend Invocation
//===----------------------------------------------------------------------===//

static bool isElmFile(llvm::StringRef path) {
    return path.ends_with(".elm");
}

static bool isMlirFile(llvm::StringRef path) {
    return path.ends_with(".mlir");
}

static bool isObjectFile(llvm::StringRef path) {
    return path.ends_with(".o");
}

/// Walk up from `startPath` looking for a directory containing elm.json.
static std::string findElmProjectRoot(const std::string &startPath) {
    llvm::SmallString<256> dir(startPath);
    llvm::sys::path::remove_filename(dir); // start from file's parent

    while (!dir.empty()) {
        llvm::SmallString<256> candidate(dir);
        llvm::sys::path::append(candidate, "elm.json");
        if (llvm::sys::fs::exists(candidate))
            return std::string(dir);

        // parent_path returns a StringRef into dir's buffer, so copy it
        // to a temporary before reassigning.
        std::string parent(llvm::sys::path::parent_path(dir));
        if (parent == std::string(dir))
            break; // reached filesystem root
        dir = parent;
    }
    return "";
}

static int compileElmToMlir(const std::string &elmFile,
                             const std::string &mlirOutput) {
    if (frontendRunner.empty()) {
        llvm::errs() << "Error: --frontend=<path> is required for .elm input\n";
        return 1;
    }

    auto nodeOrErr = llvm::sys::findProgramByName("node");
    if (!nodeOrErr) {
        llvm::errs() << "Error: 'node' not found in PATH\n";
        return 1;
    }

    // Determine the Elm project directory (must contain elm.json).
    std::string projectDir = workDir;
    if (projectDir.empty())
        projectDir = findElmProjectRoot(elmFile);
    if (projectDir.empty()) {
        llvm::errs() << "Error: Could not find elm.json for '" << elmFile
                     << "'. Use --workdir=<dir> to specify the project root.\n";
        return 1;
    }

    // Make elmFile and mlirOutput absolute before changing cwd.
    llvm::SmallString<256> absElm(elmFile);
    llvm::sys::fs::make_absolute(absElm);
    llvm::SmallString<256> absOutput(mlirOutput);
    llvm::sys::fs::make_absolute(absOutput);

    std::string outputArg = "--output=" + std::string(absOutput);

    llvm::SmallVector<llvm::StringRef> args;
    args.push_back(*nodeOrErr);
    args.push_back(frontendRunner);
    args.push_back("make");
    args.push_back(outputArg);
    args.push_back(llvm::StringRef(absElm));

    if (verbose) {
        llvm::errs() << "[eco-boot] frontend (cwd=" << projectDir << "):";
        for (auto &a : args)
            llvm::errs() << " " << a;
        llvm::errs() << "\n";
    }

    // Save current directory, cd to project root, invoke frontend, restore.
    llvm::SmallString<256> savedCwd;
    llvm::sys::fs::current_path(savedCwd);
    if (auto ec = llvm::sys::fs::set_current_path(projectDir)) {
        llvm::errs() << "Error: Could not change to directory '"
                     << projectDir << "': " << ec.message() << "\n";
        return 1;
    }

    std::string errMsg;
    int rc = llvm::sys::ExecuteAndWait(
        *nodeOrErr, args, /*env=*/std::nullopt,
        /*redirects=*/{}, /*secondsToWait=*/0, /*memoryLimit=*/0, &errMsg);

    // Restore original working directory.
    llvm::sys::fs::set_current_path(savedCwd);

    if (rc != 0) {
        llvm::errs() << "Error: frontend compilation failed";
        if (!errMsg.empty())
            llvm::errs() << ": " << errMsg;
        llvm::errs() << "\n";
        return 1;
    }
    return 0;
}

//===----------------------------------------------------------------------===//
// MLIR Loading and Pipeline
//===----------------------------------------------------------------------===//

static OwningOpRef<ModuleOp> loadMLIR(MLIRContext &context,
                                       llvm::SourceMgr &sourceMgr) {
    auto module = parseSourceFile<ModuleOp>(sourceMgr, &context);
    if (!module)
        llvm::errs() << "Error: Failed to parse MLIR file\n";
    return module;
}

static int runPipeline(ModuleOp module, eco::LoweringStats &stats) {
    PassManager pm(module->getName());

    if (failed(applyPassManagerCLOptions(pm)))
        return 1;

    // Per-pass timing — installed before passes are added so every pass
    // (including ones registered by buildEcoToLLVMPipeline) is observed.
    pm.addInstrumentation(stats.makePassInstrumentation());

    eco::EcoPipelineOptions pipeOpts;
    pipeOpts.enableUnboxedAgg = enableUnboxedAgg;
    eco::buildEcoToLLVMPipeline(pm, pipeOpts);

    if (failed(pm.run(module)))
        return 1;

    return 0;
}

//===----------------------------------------------------------------------===//
// LLVM IR Translation
//===----------------------------------------------------------------------===//

static std::unique_ptr<llvm::Module> translateToLLVMIR(
    ModuleOp module, llvm::LLVMContext &llvmContext) {
    registerBuiltinDialectTranslation(*module->getContext());
    registerLLVMDialectTranslation(*module->getContext());

    auto llvmModule = translateModuleToLLVMIR(module, llvmContext);
    if (!llvmModule) {
        llvm::errs() << "Error: Failed to translate MLIR to LLVM IR\n";
        return nullptr;
    }

    // Rename "main" to "eco_main" to avoid conflict with C main()
    // in the entry wrapper.
    if (auto *mainFn = llvmModule->getFunction("main")) {
        mainFn->setName("eco_main");
    }

    return llvmModule;
}

//===----------------------------------------------------------------------===//
// Target Machine Creation
//===----------------------------------------------------------------------===//

static std::unique_ptr<llvm::TargetMachine> createTargetMachine(
    llvm::Module &module) {
    auto triple = llvm::sys::getDefaultTargetTriple();
    module.setTargetTriple(llvm::Triple(triple));

    std::string error;
    const auto *target = llvm::TargetRegistry::lookupTarget(triple, error);
    if (!target) {
        llvm::errs() << "Error: Could not find target: " << error << "\n";
        return nullptr;
    }

    auto cpu = llvm::sys::getHostCPUName();
    llvm::SubtargetFeatures features;
    auto hostFeatures = llvm::sys::getHostCPUFeatures();
    for (auto &f : hostFeatures)
        features.AddFeature(f.first(), f.second);

    llvm::TargetOptions targetOpts;

    auto codeGenOpt = static_cast<llvm::CodeGenOptLevel>(
        std::min(optLevel.getValue(), 3u));

    auto *tm = target->createTargetMachine(
        llvm::Triple(triple),
        cpu,
        features.getString(),
        targetOpts,
        llvm::Reloc::PIC_,
        llvm::CodeModel::Small,
        codeGenOpt);

    if (!tm) {
        llvm::errs() << "Error: Could not create TargetMachine\n";
        return nullptr;
    }

    module.setDataLayout(tm->createDataLayout());
    return std::unique_ptr<llvm::TargetMachine>(tm);
}

//===----------------------------------------------------------------------===//
// Object File Emission
//===----------------------------------------------------------------------===//

static int emitObjectFile(llvm::Module &llvmModule,
                          llvm::TargetMachine &tm,
                          const std::string &outputPath) {
    std::error_code ec;
    llvm::raw_fd_ostream dest(outputPath, ec, llvm::sys::fs::OF_None);
    if (ec) {
        llvm::errs() << "Error: Could not open output file '" << outputPath
                     << "': " << ec.message() << "\n";
        return 1;
    }

    llvm::legacy::PassManager emitPM;
    if (tm.addPassesToEmitFile(emitPM, dest, nullptr,
                                llvm::CodeGenFileType::ObjectFile)) {
        llvm::errs() << "Error: Target machine can't emit object files\n";
        return 1;
    }
    emitPM.run(llvmModule);
    dest.flush();

    if (verbose)
        llvm::errs() << "[eco-boot] emitted object file: " << outputPath << "\n";

    return 0;
}

//===----------------------------------------------------------------------===//
// Linking via clang++ Driver
//===----------------------------------------------------------------------===//

static int linkExecutable(const std::string &objectFile,
                          const std::string &outputPath) {
    auto clangOrErr = llvm::sys::findProgramByName("clang++");
    if (!clangOrErr) {
        llvm::errs() << "Error: 'clang++' not found in PATH\n";
        return 1;
    }

    // Collect all library paths from the generated config header.
    // These are std::strings that must outlive the StringRef args vector.
    std::string entryLib = eco::config::entryLib;
    std::string runtimeLib = eco::config::runtimeLib;
    auto elmKernelLibs = eco::config::elmKernelLibs();
    auto ecoKernelLibs = eco::config::ecoKernelLibs();

    llvm::SmallVector<llvm::StringRef> args;
    args.push_back(*clangOrErr);
    args.push_back("-o");
    args.push_back(outputPath);
    args.push_back(objectFile);

    // Use -Wl,--start-group / --end-group to handle circular dependencies
    // between static libraries (e.g., EffectRegistry references Time/Http
    // effect managers, which in turn reference Scheduler/Platform).
    // Project .a libraries are passed by path (already static archives).
    // System libraries are linked dynamically to avoid pulling in all
    // transitive static dependencies of libcurl (nghttp2, gssapi, etc.).
    args.push_back("-Wl,--start-group");

    // Entry point wrapper
    if (!entryLib.empty())
        args.push_back(entryLib);

    // Eco runtime (GC, allocator, string/list ops, platform)
    if (!runtimeLib.empty())
        args.push_back(runtimeLib);

    // Elm kernel libraries
    for (const auto &lib : elmKernelLibs)
        args.push_back(lib);

    // Eco kernel libraries (IO: File, Console, Env, Process, MVar, Runtime, Http, Crash)
    for (const auto &lib : ecoKernelLibs)
        args.push_back(lib);

    args.push_back("-lpthread");
    args.push_back("-lm");
    args.push_back("-lstdc++");
    args.push_back("-lcurl");
    args.push_back("-lssl");
    args.push_back("-lcrypto");
    // Optional kernel system libs detected at CMake configure time — currently
    // libzip when present (Http.cpp's archive-extraction path). Empty when the
    // host had no libzip; Http.cpp falls back to stubs in that case.
    auto kernelSysLibs = eco::config::kernelSystemLibs();
    for (const auto &lib : kernelSysLibs)
        args.push_back(lib);
    args.push_back("-lzip");
    // LLVM libunwind — passed by absolute path (NOT -lunwind) so the linker
    // cannot silently pick up the system (nongnu) libunwind instead.
    args.push_back(eco::config::unwindLib);
    args.push_back("-Wl,--end-group");

    // Embed an rpath entry so the produced AOT binary can locate the LLVM
    // libunwind shared library at runtime without LD_LIBRARY_PATH.
    std::string rpathArg = std::string("-Wl,-rpath,") + eco::config::unwindLibDir;
    args.push_back(rpathArg);

    if (verbose) {
        llvm::errs() << "[eco-boot] link:";
        for (auto &a : args)
            llvm::errs() << " " << a;
        llvm::errs() << "\n";
    }

    std::string errMsg;
    int rc = llvm::sys::ExecuteAndWait(
        *clangOrErr, args, /*env=*/std::nullopt,
        /*redirects=*/{}, /*secondsToWait=*/0, /*memoryLimit=*/0, &errMsg);
    if (rc != 0) {
        llvm::errs() << "Error: Linking failed";
        if (!errMsg.empty())
            llvm::errs() << ": " << errMsg;
        llvm::errs() << "\n";
        return 1;
    }

    if (verbose)
        llvm::errs() << "[eco-boot] linked executable: " << outputPath << "\n";

    return 0;
}

//===----------------------------------------------------------------------===//
// Output Path Logic
//===----------------------------------------------------------------------===//

static std::string getOutputPath() {
    if (!outputFilename.empty())
        return outputFilename;

    switch (emitAction) {
    case EmitExe:
        return "a.out";
    case EmitObj: {
        llvm::SmallString<256> path(inputFilename.getValue());
        llvm::sys::path::replace_extension(path, ".o");
        return std::string(path);
    }
    case EmitLLVM: {
        llvm::SmallString<256> path(inputFilename.getValue());
        llvm::sys::path::replace_extension(path, ".ll");
        return std::string(path);
    }
    case EmitMLIR:
        return "-"; // stdout
    }
    return "a.out";
}

//===----------------------------------------------------------------------===//
// Main
//===----------------------------------------------------------------------===//

int main(int argc, char **argv) {
    llvm::InitLLVM initLLVM(argc, argv);

    // Initialize LLVM native target for object emission.
    llvm::InitializeNativeTarget();
    llvm::InitializeNativeTargetAsmPrinter();
    llvm::InitializeNativeTargetAsmParser();

    registerAsmPrinterCLOptions();
    registerMLIRContextCLOptions();
    registerPassManagerCLOptions();

    cl::ParseCommandLineOptions(argc, argv,
        "Eco native compiler\n\n"
        "Compiles Elm source files or MLIR to native x86-64 Linux executables.\n");

    std::string output = getOutputPath();

    // Lifetime spans the whole driver — phases below add to it via Scope, and
    // we print the aggregated table just before main() returns.
    eco::LoweringStats stats;

    // Fast path: when the input is an already-emitted object file, skip the
    // MLIR parse / lowering / LLVM-IR / RS4GC / object-emission pipeline and
    // go straight to the link step. This is the C++-only edit-test loop:
    // .mlir hasn't changed, only the runtime/kernel libraries have, so the
    // cached .o still reflects the current Elm-side compiler and only
    // re-linking is required.
    if (isObjectFile(inputFilename)) {
        if (emitAction != EmitExe) {
            llvm::errs()
                << "Error: when input is an object file, --emit must be 'exe' "
                << "(default); the MLIR/LLVM pipeline does not run for .o "
                << "input.\n";
            return 1;
        }
        int rc;
        {
            eco::LoweringStats::Scope scope(stats, "Link (clang++ driver)");
            rc = linkExecutable(inputFilename, output);
        }
        if (printStats)
            stats.print(llvm::errs());
        return rc;
    }

    // Step 1: Get MLIR input (either directly or via frontend compilation)
    std::string mlirFile;
    std::string tempMlirFile;

    if (isMlirFile(inputFilename)) {
        mlirFile = inputFilename;
    } else if (isElmFile(inputFilename)) {
        if (emitAction == EmitMLIR) {
            // Just run the frontend and output the MLIR
            std::string mlirOutput = (output == "-") ? "/dev/stdout" : output;
            int rc;
            {
                eco::LoweringStats::Scope scope(stats, "frontend (Elm -> MLIR)");
                rc = compileElmToMlir(inputFilename, mlirOutput);
            }
            if (printStats)
                stats.print(llvm::errs());
            return rc;
        }

        // Create a temp file for the MLIR intermediate
        llvm::SmallString<256> tempPath;
        if (auto ec = llvm::sys::fs::createTemporaryFile(
                "eco-boot", "mlir", tempPath)) {
            llvm::errs() << "Error: Could not create temp file: "
                         << ec.message() << "\n";
            return 1;
        }
        tempMlirFile = std::string(tempPath);
        mlirFile = tempMlirFile;

        {
            eco::LoweringStats::Scope scope(stats, "frontend (Elm -> MLIR)");
            if (compileElmToMlir(inputFilename, mlirFile) != 0) {
                llvm::sys::fs::remove(tempMlirFile);
                return 1;
            }
        }
    } else {
        llvm::errs()
            << "Error: Input file must be .elm, .mlir, or .o (re-link only)\n";
        return 1;
    }

    // Step 2: Parse MLIR
    DialectRegistry registry;
    eco::registerRequiredDialects(registry);

    MLIRContext context(registry);
    eco::loadRequiredDialects(context);
    context.allowUnregisteredDialects();

    std::string errorMessage;
    auto inputFile = openInputFile(mlirFile, &errorMessage);
    if (!inputFile) {
        llvm::errs() << "Error: " << errorMessage << "\n";
        if (!tempMlirFile.empty())
            llvm::sys::fs::remove(tempMlirFile);
        return 1;
    }

    llvm::SourceMgr sourceMgr;
    sourceMgr.AddNewSourceBuffer(std::move(inputFile), llvm::SMLoc());

    OwningOpRef<ModuleOp> module;
    {
        eco::LoweringStats::Scope scope(stats, "MLIR parse + verify");
        module = loadMLIR(context, sourceMgr);
        if (!module) {
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }

        if (failed(verify(*module))) {
            llvm::errs() << "Error: Module verification failed\n";
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }
    }

    // Step 3: Run MLIR lowering pipeline (Eco -> LLVM dialect)
    {
        eco::LoweringStats::Scope scope(stats, "MLIR lowering pipeline");
        if (runPipeline(*module, stats) != 0) {
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }
    }

    // Step 4: Translate to LLVM IR
    llvm::LLVMContext llvmContext;
    std::unique_ptr<llvm::Module> llvmModule;
    {
        eco::LoweringStats::Scope scope(stats, "MLIR -> LLVM IR translation");
        llvmModule = translateToLLVMIR(*module, llvmContext);
        if (!llvmModule) {
            if (!tempMlirFile.empty())
                llvm::sys::fs::remove(tempMlirFile);
            return 1;
        }
    }

    // Step 5: Create TargetMachine and set DataLayout BEFORE RS4GC (Phase 3
    // of the pipeline-convergence plan — matches the JIT path's ordering).
    // createTargetMachine() is opt-level aware; that is load-bearing for
    // AOT -O0..-O3 codegen and must stay in this tool's local helper.
    std::unique_ptr<llvm::TargetMachine> tm;
    {
        eco::LoweringStats::Scope scope(stats, "TargetMachine init");
        tm = createTargetMachine(*llvmModule);
        if (!tm)
            return 1;
    }

    // Step 6: Run RS4GC + optional pre/post dumps + frame-pointer attributes
    // via the shared backend driver.
    {
        eco::LoweringStats::Scope scope(stats, "LLVM RS4GC pipeline");
        eco::EcoBackendJob job;
        job.kind = eco::BackendKind::EmitObjectFile;
        job.tm = tm.get();
        job.optLevel = optLevel > 0
            ? static_cast<llvm::CodeGenOptLevel>(std::min(optLevel.getValue(), 3u))
            : llvm::CodeGenOptLevel::None;
        job.needsFramePointerAttr = true;
        job.preRS4GCDumpPath = dumpPreRS4GCIR;
        job.postRS4GCDumpPath = dumpRS4GCIR;
        if (auto err = eco::runEcoBackend(*llvmModule, job)) {
            llvm::errs() << "Error: RS4GC failed: " << err << "\n";
            return 1;
        }
    }

    // Clean up temp MLIR file now that we're done with it
    if (!tempMlirFile.empty())
        llvm::sys::fs::remove(tempMlirFile);

    // Step 6: Optionally run LLVM optimization passes
    if (optLevel > 0) {
        eco::LoweringStats::Scope scope(stats, "LLVM optimization (-O>0)");
        auto optPipeline = makeOptimizingTransformer(
            optLevel, /*sizeLevel=*/0, /*targetMachine=*/tm.get());
        if (auto err = optPipeline(llvmModule.get())) {
            llvm::errs() << "Error: LLVM optimization failed: " << err << "\n";
            return 1;
        }
    }

    // Handle LLVM IR output mode
    if (emitAction == EmitLLVM) {
        {
            eco::LoweringStats::Scope scope(stats, "Emit LLVM IR");
            if (output == "-") {
                llvm::outs() << *llvmModule << "\n";
            } else {
                std::error_code ec;
                llvm::raw_fd_ostream out(output, ec, llvm::sys::fs::OF_None);
                if (ec) {
                    llvm::errs() << "Error: Could not open output file: "
                                 << ec.message() << "\n";
                    return 1;
                }
                out << *llvmModule << "\n";
            }
        }
        if (printStats)
            stats.print(llvm::errs());
        return 0;
    }

    // Step 7: Emit object file
    std::string objFile;
    std::string tempObjFile;

    if (emitAction == EmitObj) {
        objFile = output;
    } else {
        // Create temp object file for linking
        llvm::SmallString<256> tempPath;
        if (auto ec = llvm::sys::fs::createTemporaryFile(
                "eco-boot", "o", tempPath)) {
            llvm::errs() << "Error: Could not create temp file: "
                         << ec.message() << "\n";
            return 1;
        }
        tempObjFile = std::string(tempPath);
        objFile = tempObjFile;
    }

    {
        eco::LoweringStats::Scope scope(stats, "Object file emission");
        if (emitObjectFile(*llvmModule, *tm, objFile) != 0) {
            if (!tempObjFile.empty())
                llvm::sys::fs::remove(tempObjFile);
            return 1;
        }
    }

    if (emitAction == EmitObj) {
        if (printStats)
            stats.print(llvm::errs());
        return 0;
    }

    // Step 8: Link executable
    int rc;
    {
        eco::LoweringStats::Scope scope(stats, "Link (clang++ driver)");
        rc = linkExecutable(objFile, output);
    }

    // Clean up temp object file
    if (!tempObjFile.empty())
        llvm::sys::fs::remove(tempObjFile);

    if (printStats)
        stats.print(llvm::errs());

    return rc;
}
