//===- eco_entry.cpp - Entry point wrapper for AOT-compiled binaries ------===//
//
// Provides the C main() for executables produced by eco-boot. Initializes the
// Eco runtime (GC, effect managers, globals) then calls the Elm program's
// main function (renamed to eco_main by eco-boot to avoid symbol clash).
//
//===----------------------------------------------------------------------===//

#include "../allocator/Allocator.hpp"
#include "../allocator/StackMap.hpp"
#include "../allocator/GCStats.hpp"
#include "../platform/StackMapSection.hpp"
#include "../../eco-kernel-cpp/src/eco/Env.hpp"

#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <atomic>
#include <csignal>
#include <iostream>

#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <process.h>   // _beginthreadex
#include <io.h>        // _write, _fileno
// Win64 has no SIGBUS, SIGQUIT, SIGPIPE. The CRT does honour signal() for
// SIGABRT/SIGSEGV/SIGFPE/SIGILL/SIGINT/SIGTERM (subset of POSIX), and
// SetConsoleCtrlHandler delivers Ctrl+C / Ctrl+Break / Close / Logoff /
// Shutdown — see installStatsHandlers() below.
#else
#include <pthread.h>
#include <unistd.h>
#endif

// Default stack size for AOT-compiled Eco binaries (64 MB).
// The Elm compiler's recursive type decoders can exhaust the default 8 MB
// Linux stack when self-compiling, mirroring the Node.js --stack-size=65536.
static constexpr size_t ECO_DEFAULT_STACK_SIZE = 64ULL * 1024 * 1024;

// Parse the LLVM stackmaps section from the running executable so the GC
// can discover stack roots at safepoints. Section discovery is the platform
// seam in platform/StackMapSection.hpp (ELF phdr walk / Mach-O
// getsectiondata).
static void initStackMapFromSelf() {
    auto sec = eco::platform::findStackMapSection(/*addr=*/nullptr);

    if (sec.data && sec.size > 0) {
        // The stackmaps section's relocations are resolved by the loader,
        // so function addresses are already absolute. Pass loadBase=0 (no
        // additional relocation needed).
        bool ok = Elm::globalStackMap().parse(sec.data, sec.size, /*loadBase=*/0);
#if ECO_GC_DEBUG
        fprintf(stderr, "[init] stackmap: data=%p size=%zu parsed=%d hasRecords=%d\n",
                (void*)sec.data, sec.size, (int)ok,
                (int)Elm::globalStackMap().hasRecords());
#endif
        (void)ok;
    } else {
#if ECO_GC_DEBUG
        fprintf(stderr, "[init] stackmap: NOT FOUND (data=%p size=%zu)\n",
                (void*)sec.data, sec.size);
#endif
    }
}

extern "C" {

// Generated by EcoToLLVM pass when eco.global ops are present.
// Declared weak so modules without globals link correctly. On Windows there
// is no __attribute__((weak)); a weak external symbol is emitted via
// /alternatename in the link line by EcoNativeDriver instead, and the
// declaration here drops the GCC attribute.
#if defined(_WIN32)
void __eco_init_globals();
#else
__attribute__((weak)) void __eco_init_globals();
#endif

// The Elm main function, renamed from "main" to "eco_main" by eco-boot
// during LLVM IR emission to avoid conflict with this C main.
int64_t eco_main();

// Effect manager registration (from ElmKernel_EffectRegistry).
void eco_register_all_effect_managers();

// Eco kernel GC root registration (MVar + Runtime saved-state).
void Eco_Kernel_register_all_gc_roots();

} // extern "C"

struct MainArgs {
    int argc;
    char **argv;
    int result;
};

static void *eco_main_thread(void *arg) {
    auto *args = static_cast<MainArgs *>(arg);

    // Initialize the generational GC and thread-local heap.
    Elm::Allocator::instance().initialize();
    Elm::Allocator::instance().initThread();

    // Register Eco kernel GC roots (MVar table, Runtime saved state) before
    // any Elm code runs so an early GC sees them.
    Eco_Kernel_register_all_gc_roots();

    // Parse the .llvm_stackmaps section so the GC can find stack roots.
    initStackMapFromSelf();

    // Register global variables as GC roots (if the module has any).
    if (__eco_init_globals)
        __eco_init_globals();

    // Store argc/argv so Eco.Kernel.Env.rawArgs can return them.
    Eco::Kernel::Env::init(args->argc, args->argv);

    // Register effect managers (Time, Http, etc.) with the scheduler.
    eco_register_all_effect_managers();

    // Run the Elm program.
    int64_t result = eco_main();

    // ECO_GC_EXIT_MAJOR=1: force one major GC after the program finishes
    // (still on the Elm thread, before teardown) so the exit stats'
    // "latest: most recent major-GC end" residency block reports the LIVE
    // retained set — rooted globals such as memoized CAF slots — rather
    // than whatever the last organic major happened to leave behind.
    // Measurement-only knob; no effect on program results.
    if (const char *exit_major = std::getenv("ECO_GC_EXIT_MAJOR");
        exit_major && exit_major[0] == '1') {
        Elm::Allocator::instance().majorGC();
    }

    // Cleanup thread-local allocator state.
    Elm::Allocator::instance().cleanupThread();

    args->result = static_cast<int>(result);
    return nullptr;
}

// ============================================================================
// GC stats reporting on exit / crash.
// ============================================================================
//
// On normal exit, an atexit handler prints the combined GC statistics. To
// also cover crashes (SIGABRT from assert(), SIGSEGV, etc.) we install a
// signal handler that prints the same stats then restores the default
// disposition and re-raises so a core dump (or the assertion message) is
// still produced.
//
// The print path uses iostreams (and acquires a recursive mutex inside
// getCombinedStats), which are not strictly async-signal-safe. In practice
// this is good enough for SIGABRT from assertion failures and for
// SIGINT/SIGTERM, which is the case Stage 7 needs. SIGSEGV from heap
// corruption may deadlock or crash inside the print — accepted risk.
#if ENABLE_GC_STATS
static std::atomic<bool> g_stats_printed{false};

static void printGCStatsOnce(const char *reason) {
    if (g_stats_printed.exchange(true)) return;
    // Use write() syscall for the marker (async-signal-safe). If the
    // process dies mid-print we still know the handler ran.
    {
        char buf[128];
        int n = std::snprintf(buf, sizeof(buf),
                              "\n[gc-stats] %s — printing GC statistics\n",
                              reason);
        if (n > 0) {
#if defined(_WIN32)
            ::_write(::_fileno(stderr), buf, static_cast<unsigned int>(n));
#else
            ::write(STDERR_FILENO, buf, static_cast<size_t>(n));
#endif
        }
    }
    Elm::Allocator::instance().getCombinedStats().print();
    // Flush BOTH the C++ stream buffer and the underlying FILE* buffer.
    // print() writes via std::cout, which has its own buffer separate from
    // stdout's; without the explicit cout.flush(), an immediate
    // std::raise(sig) → SIG_DFL termination can drop everything past the
    // last sync point.
    std::cout.flush();
    std::fflush(stdout);
    std::fflush(stderr);
}

static void atexitPrintStats() {
    // ECO_GC_EXIT_MAJOR=1: the Elm program usually terminates via the
    // kernel's exit (std::exit), so the post-eco_main() hook in the runner
    // thread never runs. atexit handlers execute on the exiting thread —
    // normally the Elm thread — so the TL heap is still valid here (guarded:
    // after cleanupThread(), or from a foreign thread, it is null and the
    // forced major is skipped). Doing it before the print makes the
    // "latest: most recent major-GC end" residency block report the live
    // retained set at exit. NOT done on the signal path — running a GC in a
    // signal context is unsafe.
    if (const char *exit_major = std::getenv("ECO_GC_EXIT_MAJOR");
        exit_major && exit_major[0] == '1' &&
        Elm::Allocator::instance().getCurrentThreadHeap() != nullptr) {
        Elm::Allocator::instance().majorGC();
    }
    printGCStatsOnce("normal exit");
}

static void signalPrintStats(int sig) {
    // Restore the default handler so the re-raise produces the usual
    // termination effect (core dump for SIGSEGV/SIGABRT, exit for SIGTERM).
    std::signal(sig, SIG_DFL);
    const char *name = "signal";
    switch (sig) {
        case SIGABRT: name = "SIGABRT"; break;
        case SIGSEGV: name = "SIGSEGV"; break;
        case SIGFPE:  name = "SIGFPE";  break;
        case SIGILL:  name = "SIGILL";  break;
        case SIGINT:  name = "SIGINT";  break;
        case SIGTERM: name = "SIGTERM"; break;
#if !defined(_WIN32)
        // SIGBUS, SIGQUIT, SIGPIPE do not exist on Win64.
        case SIGBUS:  name = "SIGBUS";  break;
        case SIGQUIT: name = "SIGQUIT"; break;
        case SIGPIPE: name = "SIGPIPE"; break;
#endif
    }
    printGCStatsOnce(name);
    std::raise(sig);
}

#if defined(_WIN32)
// Translate Ctrl+C / Ctrl+Break / Close / Logoff / Shutdown into the same
// GC-stats print path that POSIX signals trigger. Win64 has no SIGINT/SIGTERM
// equivalent that POSIX `signal()` can attach to for these events — the CRT
// only raises SIGINT for Ctrl+C and SIGTERM never — so we register a console
// control handler explicitly. Returning FALSE lets the next handler in the
// chain run (usually the default, which terminates).
static BOOL WINAPI consoleCtrlHandler(DWORD ctrlType) {
    const char* name = "console-ctrl";
    switch (ctrlType) {
        case CTRL_C_EVENT:        name = "CTRL_C_EVENT";        break;
        case CTRL_BREAK_EVENT:    name = "CTRL_BREAK_EVENT";    break;
        case CTRL_CLOSE_EVENT:    name = "CTRL_CLOSE_EVENT";    break;
        case CTRL_LOGOFF_EVENT:   name = "CTRL_LOGOFF_EVENT";   break;
        case CTRL_SHUTDOWN_EVENT: name = "CTRL_SHUTDOWN_EVENT"; break;
    }
    printGCStatsOnce(name);
    return FALSE; // chain to the default handler (which terminates).
}
#endif

static void installStatsHandlers() {
    std::atexit(atexitPrintStats);

#if !defined(_WIN32)
    // Ignore SIGPIPE so a write to a closed pipe (e.g. `eco ... | head`) returns
    // EPIPE to the kernel write path — surfaced as Eco.IO.Error.BrokenPipe and
    // handled locally — instead of terminating the process (see IO_ERR_001).
    // No equivalent on Windows: pipe-write failures already surface as
    // ERROR_BROKEN_PIPE → ::errno = EPIPE in the CRT, no signal involved.
    std::signal(SIGPIPE, SIG_IGN);

    struct sigaction sa{};
    sa.sa_handler = signalPrintStats;
    sigemptyset(&sa.sa_mask);
    // Don't set SA_RESETHAND; we restore SIG_DFL inside the handler.
    sa.sa_flags = SA_NODEFER;
    int signals[] = {
        SIGABRT, SIGSEGV, SIGBUS, SIGFPE, SIGILL,
        SIGINT, SIGTERM, SIGQUIT
    };
    for (int s : signals) {
        sigaction(s, &sa, nullptr);
    }
#else
    // Win64 path. The CRT honours signal() for the synchronous fault
    // signals (SIGABRT from abort(), SIGSEGV/SIGFPE/SIGILL from vectored EH
    // when re-raised) plus SIGINT (Ctrl+C) and SIGTERM (programmatic
    // raise(SIGTERM)). Console close / logoff / shutdown come through the
    // separate SetConsoleCtrlHandler chain.
    int signals[] = { SIGABRT, SIGSEGV, SIGFPE, SIGILL, SIGINT, SIGTERM };
    for (int s : signals) {
        std::signal(s, signalPrintStats);
    }
    SetConsoleCtrlHandler(consoleCtrlHandler, TRUE);
#endif
}
#else
static void installStatsHandlers() {}
#endif

int main(int argc, char **argv) {
    // Disable stdio buffering so progress lines and (more importantly) the
    // GCStats summary printed by signal handlers reach the captured log
    // files even when the process is killed mid-print. Stdout in particular
    // is fully-buffered by default when not connected to a terminal.
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    std::setvbuf(stderr, nullptr, _IONBF, 0);

    installStatsHandlers();

    MainArgs args{argc, argv, 0};

#if defined(_WIN32)
    // _beginthreadex is the C-runtime-aware equivalent of pthread_create.
    // It accepts the stack-size in bytes (0 = system default) plus a
    // function pointer using the __stdcall + unsigned-return convention.
    // We wrap the POSIX-shaped eco_main_thread so the runtime stays
    // platform-neutral above.
    struct WinAdapter {
        static unsigned __stdcall run(void* a) {
            eco_main_thread(a);
            return 0;
        }
    };
    uintptr_t h = ::_beginthreadex(nullptr, ECO_DEFAULT_STACK_SIZE,
                                   &WinAdapter::run, &args, 0, nullptr);
    if (h == 0) {
        // Fallback: run on main thread if thread creation fails.
        eco_main_thread(&args);
    } else {
        ::WaitForSingleObject(reinterpret_cast<HANDLE>(h), INFINITE);
        ::CloseHandle(reinterpret_cast<HANDLE>(h));
    }
#else
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setstacksize(&attr, ECO_DEFAULT_STACK_SIZE);

    pthread_t thread;
    if (pthread_create(&thread, &attr, eco_main_thread, &args) != 0) {
        // Fallback: run on main thread if thread creation fails.
        eco_main_thread(&args);
    } else {
        pthread_join(thread, nullptr);
    }

    pthread_attr_destroy(&attr);
#endif

#if defined(_WIN32)
    // Win64 teardown hard-exit. AOT Elm binaries drive the Scheduler event
    // loop, which lazily starts detached service worker threads
    // (TimerService unconditionally; Http/Wait on demand) that park forever
    // in std::condition_variable::wait and are never signalled to stop.
    // On POSIX, returning from main lets the process die and these detached
    // threads are harmlessly abandoned. On the MSVC /MT CRT, returning runs
    // exit() -> ExitProcess, which terminates those parked threads *mid-lock*
    // and then runs DLL_PROCESS_DETACH + static destructors needing the same
    // lock -> intermittent teardown deadlock (process hangs as a zombie with
    // all work done). The program's work and output are already complete
    // (stdio is unbuffered above), so exit hard exactly as POSIX effectively
    // does. TerminateProcess (unlike ExitProcess) skips DLL detach entirely,
    // so it cannot deadlock on a lock held by a terminated worker thread.
    // stdout/stderr are _IONBF (set at the top of main), so nothing is
    // buffered; flush the C++ streams defensively, then terminate.
    std::cout.flush();
    std::cerr.flush();
    ::TerminateProcess(::GetCurrentProcess(), static_cast<UINT>(args.result));
    // TerminateProcess is asynchronous; if it ever returns, do NOT fall through
    // to the CRT teardown (the very deadlock we are avoiding) — spin until the
    // OS process rundown reaps this thread.
    for (;;) { ::Sleep(1000); }
#endif
    return args.result;
}
