#!/bin/sh
# gen-tls-fixtures.sh — regenerate test/eco-system/src/TlsFixtures.elm
# (plans/eco-system-sockets.md §4 S5 step 2).
#
#   usage: sh test/eco-system/scripts/gen-tls-fixtures.sh [<repo-root>]
#
# Generated once and checked in: the TLS tests never call openssl. Uses only
# the `openssl` CLI (OpenSSL 1.1.1 or 3.x):
#
#   * a test CA (self-signed, 100 years);
#   * a server certificate for DNS:localhost, IP:127.0.0.1 signed by the CA
#     (100 years);
#   * an EXPIRED server certificate (same names, signed by the CA) valid only
#     from 2000-01-01 to 2001-01-01, made with `openssl ca -startdate/-enddate`
#     and a throwaway `openssl ca` configuration and database in a temp dir;
#   * a self-signed certificate for the same names (not signed by the CA).
#
# Keys are EC P-256 (small and fast). Every PEM becomes a String constant in
# TlsFixtures.elm, a module without `main` (the E2E harness only runs modules
# with a top-level main, sockets plan SF13).

set -eu

ROOT="${1:-$(cd "$(dirname "$0")/../../.." && pwd)}"
OUT="$ROOT/test/eco-system/src/TlsFixtures.elm"
DAYS=36500

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT INT TERM
cd "$TMP"

key() {
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$1" 2>/dev/null
}

cat > san.ext <<'EOF'
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost, IP:127.0.0.1
EOF

# --- The test CA ----------------------------------------------------------------
key ca.key
openssl req -x509 -new -key ca.key -sha256 -days "$DAYS" -subj "/CN=eco-system test CA" \
    -addext "basicConstraints=critical,CA:TRUE" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -out ca.pem

# --- The server certificate (signed by the CA) ----------------------------------
key server.key
openssl req -new -key server.key -subj "/CN=localhost" -out server.csr
openssl x509 -req -in server.csr -CA ca.pem -CAkey ca.key -CAcreateserial -sha256 \
    -days "$DAYS" -extfile san.ext -out server.pem 2>/dev/null

# --- The expired server certificate (openssl ca with explicit dates) -----------
key expired.key
openssl req -new -key expired.key -subj "/CN=localhost" -out expired.csr
mkdir -p ca-db/newcerts
: > ca-db/index.txt
echo 1000 > ca-db/serial
cat > ca.cnf <<EOF
[ ca ]
default_ca = test_ca

[ test_ca ]
dir = $TMP/ca-db
database = \$dir/index.txt
new_certs_dir = \$dir/newcerts
serial = \$dir/serial
certificate = $TMP/ca.pem
private_key = $TMP/ca.key
default_md = sha256
policy = policy_any
copy_extensions = none
unique_subject = no
x509_extensions = server_ext

[ policy_any ]
commonName = supplied

[ server_ext ]
basicConstraints = critical, CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:localhost, IP:127.0.0.1
EOF
openssl ca -batch -config ca.cnf -notext -in expired.csr -out expired.pem \
    -startdate 20000101000000Z -enddate 20010101000000Z 2>/dev/null

# --- The self-signed certificate -------------------------------------------------
key selfsigned.key
openssl req -x509 -new -key selfsigned.key -sha256 -days "$DAYS" -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
    -out selfsigned.pem

# Sanity: the good chain verifies, the expired one does not.
openssl verify -CAfile ca.pem server.pem > /dev/null
if openssl verify -CAfile ca.pem expired.pem > /dev/null 2>&1; then
    echo "gen-tls-fixtures: the expired certificate verifies?" >&2
    exit 1
fi

# --- TlsFixtures.elm ---------------------------------------------------------------

# An Elm triple-quoted String constant: `name = """<pem>"""`.
constant() {
    printf '\n\n%s : String\n%s =\n    """' "$1" "$1"
    cat "$2"
    printf '"""\n'
}

{
    cat <<EOF
module TlsFixtures exposing
    ( caPem
    , serverCertPem, serverKeyPem
    , expiredCertPem, expiredKeyPem
    , selfSignedCertPem, selfSignedKeyPem
    )

{-| TLS test certificates and keys (plans/eco-system-sockets.md §4 S5). Not a test: no \`main\`.

GENERATED by test/eco-system/scripts/gen-tls-fixtures.sh with $(openssl version | cut -d' ' -f1-2);
do not edit. Keys are EC P-256.

  - \`caPem\`: the test CA (100 years).
  - \`serverCertPem\` / \`serverKeyPem\`: DNS:localhost, IP:127.0.0.1, signed by the CA (100 years).
  - \`expiredCertPem\` / \`expiredKeyPem\`: the same names, signed by the CA, valid only from
    2000-01-01 to 2001-01-01.
  - \`selfSignedCertPem\` / \`selfSignedKeyPem\`: the same names, self-signed.

-}
EOF
    constant caPem ca.pem
    constant serverCertPem server.pem
    constant serverKeyPem server.key
    constant expiredCertPem expired.pem
    constant expiredKeyPem expired.key
    constant selfSignedCertPem selfsigned.pem
    constant selfSignedKeyPem selfsigned.key
} > "$OUT"

echo "gen-tls-fixtures: wrote $OUT"
