module TestLogic.Generate.CodeGen.NoAllocateOpsTest exposing (suite)

{-| Runs the no-allocation-op check on the standard catalogue of test
programs, so that the code generator starting to emit an allocation op would be
caught on a wide range of programs rather than a hand-picked few.

An _allocation op_ is an op named `eco.allocate`, `eco.allocate_ctor`,
`eco.allocate_string` or `eco.allocate_closure`. The check, owned by
`TestLogic.Generate.CodeGen.NoAllocateOps`, assumes such ops are introduced
only by a lowering step after code generation, so the MLIR the code generator
produces must contain none. No module under `src` builds one, so this suite
guards against one being introduced.

The fixture is the catalogue of `SourceIR` case modules that
`SourceIR.Suite.StandardTestSuites` collects: Elm source programs, most of
them fixed and some generated by fuzzers.

What the tests establish:

  - `suite`: each program compiles to MLIR with
    `TestLogic.TestPipeline.runToMlir`, and no op in the result, at any depth,
    has one of the four allocation op names. A program that fails to compile
    fails its test.

Among what is not tested: MLIR produced with the solver monomorphization
engine, since `runToMlir` uses the substitution engine; an op whose name only
begins with `eco.allocate`, since names are matched exactly; and any MLIR
after lowering.

-}

import SourceIR.Suite.StandardTestSuites as StandardTestSuites
import Test exposing (Test)
import TestLogic.Generate.CodeGen.NoAllocateOps exposing (expectNoAllocateOps)


{-| The test group that runs `expectNoAllocateOps` over the programs of the
standard catalogue.
-}
suite : Test
suite =
    Test.describe "CGEN_039: No Allocate Ops in Codegen"
        [ StandardTestSuites.expectSuite expectNoAllocateOps "passes no allocate ops invariant"
        ]
