module TestLogic.Generate.CodeGen.OperandTypeConsistencyTest exposing (suite)

{-| Runs the operand type consistency check on the standard catalogue of test
programs, so that the code generator writing an op's operand types out of step
with its operands would be caught on a wide range of programs rather than a
hand-picked few.

An op in generated MLIR names its operands, and for many ops the code
generator records their types separately, in the op's `_operand_types`
attribute. The check, owned by
`TestLogic.Generate.CodeGen.OperandTypeConsistency`, compares that list with
the types the operands were defined with; its docstring says which ops and
operands it leaves out.

The fixture is the catalogue of `SourceIR` case modules that
`SourceIR.Suite.StandardTestSuites` collects: Elm source programs, most of
them fixed and some generated by fuzzers.

What the tests establish:

  - `suite`: each program compiles to MLIR with
    `TestLogic.TestPipeline.runToMlir`, and in every top-level `func.func` each
    op with an `_operand_types` attribute declares as many types as it has
    operands, and each declared type equals the defined type of the operand in
    the same position. A program that fails to compile fails its test.

Among what is not tested: an op with no `_operand_types` attribute; an operand
whose name is defined nowhere in its function; and MLIR produced with the
solver monomorphization engine, since `runToMlir` uses the substitution engine.

-}

import SourceIR.Suite.StandardTestSuites as StandardTestSuites
import Test exposing (Test)
import TestLogic.Generate.CodeGen.OperandTypeConsistency exposing (expectOperandTypeConsistency)


{-| The test group that runs `expectOperandTypeConsistency` over the programs
of the standard catalogue.
-}
suite : Test
suite =
    Test.describe "CGEN_040: Operand Type Consistency"
        [ StandardTestSuites.expectSuite expectOperandTypeConsistency "passes operand type consistency invariant"
        ]
