//===- eco_embed.cpp - C embedding API implementation ----------------------===//
//
// Implements eco_app_start/stop/join for hosts that link an Eco-compiled
// Elm program as a library (.so / .o). The eco-thread initialization
// mirrors eco_entry.cpp's standalone main() minus the signal handlers and
// GC-stats atexit printer (the host owns process-level concerns), plus:
//
//   - .llvm_stackmaps discovery works for BOTH executables and shared
//     objects: instead of assuming the main program, we locate the loaded
//     module that CONTAINS eco_main (the compiled Elm code) and parse its
//     stackmaps section.
//   - The scheduler holds one pendingAsync ref for the app lifetime so a
//     port-driven program does not exit when momentarily idle; the ref is
//     released by eco_app_stop.
//   - A ready handshake (PlatformRuntime::setReadyHook) makes
//     eco_app_start block until Platform.worker has dispatched its init
//     effects (or the program's main returned, for non-worker programs).
//
//===----------------------------------------------------------------------===//

#include "eco_embed.h"

#include "../allocator/Allocator.hpp"
#include "../allocator/StackMap.hpp"
#include "../platform/PlatformRuntime.hpp"
#include "../platform/PortRuntime.hpp"
#include "../platform/Scheduler.hpp"

#include <atomic>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <mutex>
#if defined(_WIN32)
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <process.h>   // _beginthreadex
// On Win64 we keep a HANDLE for the embed thread and store its thread-id
// separately for the self-equality test. WaitForSingleObject(INFINITE) is the
// pthread_join equivalent; CloseHandle releases the kernel object once join
// completes.
#else
#include <pthread.h>
#endif
#include <vector>

#include "../platform/StackMapSection.hpp"

// 64 MB, matching eco_entry.cpp (recursive decoders exhaust 8 MB).
static constexpr size_t ECO_EMBED_STACK_SIZE = 64ULL * 1024 * 1024;

extern "C" {
// Generated by EcoToLLVM when eco.global ops are present; weak so modules
// without globals link.
__attribute__((weak)) void __eco_init_globals();
// The Elm program's main, renamed from "main" during LLVM emission.
int64_t eco_main();
// Effect manager registration (ElmKernel_EffectRegistry).
void eco_register_all_effect_managers();
// Eco kernel GC roots (MVar table, Runtime saved state).
void Eco_Kernel_register_all_gc_roots();
}  // extern "C"

namespace Eco::Kernel::Env {
void init(int argc, char** argv);
}

namespace {

// Locate and parse the LLVM stackmaps section of the loaded module that
// contains `addr` (the compiled Elm code: an executable OR a dlopen'd /
// linked shared object). Section discovery is the platform seam in
// platform/StackMapSection.hpp (ELF phdr walk / Mach-O dladdr +
// getsectiondata).
void initStackMapForModuleContaining(void* addr) {
    auto sec = eco::platform::findStackMapSection(addr);

    if (sec.data && sec.size > 0) {
        // Section relocations were applied by the loader; addresses are
        // absolute. loadBase=0.
        (void)Elm::globalStackMap().parse(sec.data, sec.size, /*loadBase=*/0);
    } else {
        std::fprintf(stderr,
                     "eco embed: warning: .llvm_stackmaps not found for the "
                     "module containing eco_main; GC stack roots will be "
                     "missing\n");
    }
}

// ---------------------------------------------------------------------------
// App state
// ---------------------------------------------------------------------------

struct EmbedState {
    std::atomic<bool> started{false};
#if defined(_WIN32)
    HANDLE thread = nullptr;
    DWORD threadId = 0;
#else
    pthread_t thread{};
#endif
    std::atomic<bool> threadValid{false};
    std::atomic<int> exitCode{0};
    std::atomic<bool> stopped{false};

    // Ready handshake: posted by the PlatformRuntime ready hook (worker
    // programs) or by thread exit (plain programs / early failure).
    std::mutex readyMutex;
    std::condition_variable readyCV;
    bool ready = false;

    // Serializes eco_app_join: pthread_join on the same thread from two
    // callers concurrently is undefined behaviour.
    std::mutex joinMutex;

    int argc = 0;
    char** argv = nullptr;

    // Host-supplied flags JSON, applied ON THE ECO THREAD (PlatformRuntime
    // must not be constructed from a host thread: its constructor registers
    // a GC root scanner with the constructing thread's RootSet).
    std::string flagsJson;
    bool hasFlags = false;

    // Host idle/busy hook (see eco_set_idle_hook). Stashed on the host
    // thread before start; applied to the Scheduler ON THE ECO THREAD.
    void (*idleHook)(int busy, void* user) = nullptr;
    void* idleHookUser = nullptr;
};

EmbedState& state() {
    static EmbedState s;
    return s;
}

// Scheduler ActivityHook → host idle hook. Runs on the eco thread; forwards
// the busy/idle transition to the host callback registered via
// eco_set_idle_hook (the N-API addon refs/unrefs a keepalive there).
void schedActivityTrampoline(bool busy, void* /*user*/) {
    auto& s = state();
    if (s.idleHook)
        s.idleHook(busy ? 1 : 0, s.idleHookUser);
}

void postReady() {
    auto& s = state();
    {
        std::lock_guard<std::mutex> lk(s.readyMutex);
        s.ready = true;
    }
    s.readyCV.notify_all();
}

void readyHookTrampoline(void* /*user*/) { postReady(); }

// Stop the eco thread when the process exits abruptly (a host calling
// exit()/process.exit() without eco_app_stop). Registered ON the eco
// thread, before any of the runtime's lazily-constructed statics, so it
// runs BEFORE the destructors of everything registered earlier (atexit is
// LIFO) — without it, static teardown frees memory under a live thread
// and glibc reports malloc corruption. The key runtime singletons
// (Scheduler/PlatformRuntime/PortRuntime) are additionally leaked so
// their (later-registered) destructors cannot race either.
void atexitStopEcoThread() {
    eco_app_stop();
    // If exit() was called FROM the eco thread (e.g. Eco.Process.exit),
    // joining ourselves would deadlock (musl) or fail with EDEADLK
    // (glibc); the thread is about to die with the process anyway.
    auto& s = state();
    if (s.threadValid.load()) {
#if defined(_WIN32)
        if (GetCurrentThreadId() == s.threadId) return;
#else
        if (pthread_equal(pthread_self(), s.thread)) return;
#endif
    }
    eco_app_join();
}

void* ecoEmbedThread(void* /*arg*/) {
    auto& s = state();

    std::atexit(atexitStopEcoThread);

    // Mirrors eco_entry.cpp eco_main_thread (no signal handlers, no
    // GC-stats atexit — the host owns those process-level concerns).
    Elm::Allocator::instance().initialize();
    Elm::Allocator::instance().initThread();
    Eco_Kernel_register_all_gc_roots();
    initStackMapForModuleContaining(reinterpret_cast<void*>(&eco_main));
    if (__eco_init_globals) __eco_init_globals();
    Eco::Kernel::Env::init(s.argc, s.argv);
    eco_register_all_effect_managers();

    // First touches of PlatformRuntime and Scheduler happen HERE, on the
    // eco thread, so their constructors register their GC root scanners
    // with this thread's RootSet (the thread that actually collects).
    auto& platform = Elm::Platform::PlatformRuntime::instance();
    platform.setReadyHook(readyHookTrampoline, nullptr);
    if (s.hasFlags) {
        platform.setPendingFlagsJson(s.flagsJson);
    }

    // Hold the event loop open for the app lifetime (released by
    // eco_app_stop). Taken before eco_main so the loop can never observe
    // zero refs and exit between init and the host's first send.
    auto& sched = Elm::Platform::Scheduler::instance();
    sched.incrementPendingAsync();
    // That single lifetime hold is not "real work": tell the scheduler to
    // discount it when reporting host liveness, and wire the idle/busy
    // transitions through to the host hook (if any) so a Node loop stays
    // alive exactly while the program is busy.
    sched.setLivenessBaseline(1);
    if (s.idleHook)
        sched.setActivityHook(schedActivityTrampoline, nullptr);

    int64_t result = eco_main();

    Elm::Allocator::instance().cleanupThread();
    s.exitCode.store(static_cast<int>(result));

    // If the ready hook never fired (non-worker program, or init crashed
    // out cleanly), release the start handshake now.
    postReady();
    return nullptr;
}

}  // namespace

// ---------------------------------------------------------------------------
// C ABI
// ---------------------------------------------------------------------------

extern "C" {

int eco_app_start(int argc, char** argv, const char* flags_json) {
    auto& s = state();

    bool expected = false;
    if (!s.started.compare_exchange_strong(expected, true)) {
        return ECO_APP_ERR_ALREADY_STARTED;
    }

    s.argc = argc;
    s.argv = argv;

    // Stash the host's flags JSON; ecoEmbedThread applies it (and the
    // ready hook, and the event-loop hold) ON the eco thread. Touching
    // PlatformRuntime/Scheduler here would construct them on the host
    // thread, registering their GC root scanners with the WRONG thread's
    // RootSet — eco-thread collections would then never evacuate manager
    // closures, the flags decoder, or the run queue.
    if (flags_json != nullptr) {
        s.flagsJson = flags_json;
        s.hasFlags = true;
    }

#if defined(_WIN32)
    struct WinAdapter {
        static unsigned __stdcall run(void* a) {
            ecoEmbedThread(a);
            return 0;
        }
    };
    // _beginthreadex's last arg is `unsigned*`; DWORD == unsigned long on
    // Win64. They're the same width and value range; the reinterpret_cast
    // is so the call type-checks under strict-aliasing/-Wconversion.
    unsigned tmpId = 0;
    uintptr_t h = ::_beginthreadex(nullptr, ECO_EMBED_STACK_SIZE,
                                   &WinAdapter::run, nullptr, 0, &tmpId);
    s.threadId = tmpId;
    if (h == 0) {
        return ECO_APP_ERR_THREAD;
    }
    s.thread = reinterpret_cast<HANDLE>(h);
#else
    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setstacksize(&attr, ECO_EMBED_STACK_SIZE);
    int rc = pthread_create(&s.thread, &attr, ecoEmbedThread, nullptr);
    pthread_attr_destroy(&attr);
    if (rc != 0) {
        return ECO_APP_ERR_THREAD;
    }
#endif
    s.threadValid.store(true);

    // Block until the program is initialized (ready hook) or finished
    // (thread exit posts ready too).
    {
        std::unique_lock<std::mutex> lk(s.readyMutex);
        s.readyCV.wait(lk, [&s] { return s.ready; });
    }
    return 0;
}

void eco_app_stop(void) {
    auto& s = state();
    if (!s.started.load()) {
        // Never started: nothing to stop — and touching the Scheduler
        // here would construct it on the host thread, registering its GC
        // scanner with the wrong thread's RootSet.
        return;
    }
    bool expected = false;
    if (!s.stopped.compare_exchange_strong(expected, true)) {
        return;  // idempotent
    }
    auto& sched = Elm::Platform::Scheduler::instance();
    sched.requestStop();
    // Release the lifetime ref taken on the eco thread at startup (also
    // wakes the loop's wait predicate via the decrement's notify).
    sched.decrementPendingAsync();
}

int eco_app_join(void) {
    auto& s = state();
    std::lock_guard<std::mutex> lk(s.joinMutex);
    if (!s.threadValid.load()) {
        // Never started, or already joined: idempotent.
        return s.started.load() ? s.exitCode.load() : -1;
    }
#if defined(_WIN32)
    ::WaitForSingleObject(s.thread, INFINITE);
    ::CloseHandle(s.thread);
    s.thread = nullptr;
#else
    pthread_join(s.thread, nullptr);
#endif
    s.threadValid.store(false);
    return s.exitCode.load();
}

void eco_set_idle_hook(void (*cb)(int busy, void* user), void* user) {
    // Stash on the host thread; ecoEmbedThread applies it to the Scheduler
    // on the eco thread (constructing/touching the Scheduler here would
    // register its GC scanner with the wrong thread's RootSet). Call before
    // eco_app_start, like eco_port_subscribe.
    auto& s = state();
    s.idleHook = cb;
    s.idleHookUser = user;
}

}  // extern "C"
