//===- eco_embed.cpp - C embedding API implementation ----------------------===//
//
// Implements eco_app_start/stop/join for hosts that link an Eco-compiled
// Elm program as a library (.so / .o). The eco-thread initialization
// mirrors eco_entry.cpp's standalone main() minus the signal handlers and
// GC-stats atexit printer (the host owns process-level concerns), plus:
//
//   - .llvm_stackmaps discovery works for BOTH executables and shared
//     objects: instead of assuming the main program, we locate the loaded
//     module that CONTAINS eco_main (the compiled Elm code) and parse its
//     stackmaps section.
//   - The scheduler holds one pendingAsync ref for the app lifetime so a
//     port-driven program does not exit when momentarily idle; the ref is
//     released by eco_app_stop.
//   - A ready handshake (PlatformRuntime::setReadyHook) makes
//     eco_app_start block until Platform.worker has dispatched its init
//     effects (or the program's main returned, for non-worker programs).
//
//===----------------------------------------------------------------------===//

#include "eco_embed.h"

#include "../allocator/Allocator.hpp"
#include "../allocator/StackMap.hpp"
#include "../platform/PlatformRuntime.hpp"
#include "../platform/PortRuntime.hpp"
#include "../platform/Scheduler.hpp"

#include <atomic>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <mutex>
#include <pthread.h>
#include <vector>

#include <elf.h>
#include <link.h>

// 64 MB, matching eco_entry.cpp (recursive decoders exhaust 8 MB).
static constexpr size_t ECO_EMBED_STACK_SIZE = 64ULL * 1024 * 1024;

extern "C" {
// Generated by EcoToLLVM when eco.global ops are present; weak so modules
// without globals link.
__attribute__((weak)) void __eco_init_globals();
// The Elm program's main, renamed from "main" during LLVM emission.
int64_t eco_main();
// Effect manager registration (ElmKernel_EffectRegistry).
void eco_register_all_effect_managers();
// Eco kernel GC roots (MVar table, Runtime saved state).
void Eco_Kernel_register_all_gc_roots();
}  // extern "C"

namespace Eco::Kernel::Env {
void init(int argc, char** argv);
}

namespace {

// Locate and parse the .llvm_stackmaps section of the loaded module that
// contains `addr` (the compiled Elm code: an executable OR a dlopen'd /
// linked shared object). Adapted from eco_entry.cpp's initStackMapFromSelf,
// which only handles the main executable.
void initStackMapForModuleContaining(void* addr) {
    struct CallbackData {
        uintptr_t target;
        const uint8_t* data;
        size_t size;
    };
    CallbackData cbd{reinterpret_cast<uintptr_t>(addr), nullptr, 0};

    dl_iterate_phdr(
        [](struct dl_phdr_info* info, size_t /*size*/, void* ctx) -> int {
            auto* out = static_cast<CallbackData*>(ctx);

            // Does any PT_LOAD segment of this module contain the target?
            bool contains = false;
            for (int i = 0; i < info->dlpi_phnum; ++i) {
                const auto& ph = info->dlpi_phdr[i];
                if (ph.p_type != PT_LOAD) continue;
                uintptr_t start = info->dlpi_addr + ph.p_vaddr;
                uintptr_t end = start + ph.p_memsz;
                if (out->target >= start && out->target < end) {
                    contains = true;
                    break;
                }
            }
            if (!contains) return 0;

            // Read the module's section headers from its file on disk.
            // The main executable reports an empty name (glibc) — fall
            // back to /proc/self/exe for it.
            const char* path = info->dlpi_name;
            if (path == nullptr || path[0] == '\0') {
                path = "/proc/self/exe";
            }

            FILE* f = fopen(path, "rb");
            if (!f) return 0;

            Elf64_Ehdr ehdr;
            if (fread(&ehdr, sizeof(ehdr), 1, f) != 1) {
                fclose(f);
                return 0;
            }

            Elf64_Shdr shstrtab_hdr;
            if (fseek(f, ehdr.e_shoff + ehdr.e_shstrndx * ehdr.e_shentsize,
                      SEEK_SET) != 0 ||
                fread(&shstrtab_hdr, sizeof(shstrtab_hdr), 1, f) != 1) {
                fclose(f);
                return 0;
            }
            std::vector<char> shstrtab(shstrtab_hdr.sh_size);
            if (fseek(f, shstrtab_hdr.sh_offset, SEEK_SET) != 0 ||
                fread(shstrtab.data(), shstrtab_hdr.sh_size, 1, f) != 1) {
                fclose(f);
                return 0;
            }

            for (uint16_t i = 0; i < ehdr.e_shnum; i++) {
                Elf64_Shdr shdr;
                if (fseek(f, ehdr.e_shoff + i * ehdr.e_shentsize, SEEK_SET) !=
                        0 ||
                    fread(&shdr, sizeof(shdr), 1, f) != 1)
                    continue;
                if (shdr.sh_name >= shstrtab_hdr.sh_size) continue;
                const char* name = shstrtab.data() + shdr.sh_name;
                if (strcmp(name, ".llvm_stackmaps") == 0) {
                    out->data = reinterpret_cast<const uint8_t*>(
                        info->dlpi_addr + shdr.sh_addr);
                    out->size = shdr.sh_size;
                    fclose(f);
                    return 1;  // stop iteration
                }
            }
            fclose(f);
            return 0;
        },
        &cbd);

    if (cbd.data && cbd.size > 0) {
        // Section relocations were applied by the loader; addresses are
        // absolute. loadBase=0.
        (void)Elm::globalStackMap().parse(cbd.data, cbd.size, /*loadBase=*/0);
    } else {
        std::fprintf(stderr,
                     "eco embed: warning: .llvm_stackmaps not found for the "
                     "module containing eco_main; GC stack roots will be "
                     "missing\n");
    }
}

// ---------------------------------------------------------------------------
// App state
// ---------------------------------------------------------------------------

struct EmbedState {
    std::atomic<bool> started{false};
    pthread_t thread{};
    std::atomic<bool> threadValid{false};
    std::atomic<int> exitCode{0};
    std::atomic<bool> stopped{false};

    // Ready handshake: posted by the PlatformRuntime ready hook (worker
    // programs) or by thread exit (plain programs / early failure).
    std::mutex readyMutex;
    std::condition_variable readyCV;
    bool ready = false;

    // Serializes eco_app_join: pthread_join on the same thread from two
    // callers concurrently is undefined behaviour.
    std::mutex joinMutex;

    int argc = 0;
    char** argv = nullptr;
};

EmbedState& state() {
    static EmbedState s;
    return s;
}

void postReady() {
    auto& s = state();
    {
        std::lock_guard<std::mutex> lk(s.readyMutex);
        s.ready = true;
    }
    s.readyCV.notify_all();
}

void readyHookTrampoline(void* /*user*/) { postReady(); }

// Stop the eco thread when the process exits abruptly (a host calling
// exit()/process.exit() without eco_app_stop). Registered ON the eco
// thread, before any of the runtime's lazily-constructed statics, so it
// runs BEFORE the destructors of everything registered earlier (atexit is
// LIFO) — without it, static teardown frees memory under a live thread
// and glibc reports malloc corruption. The key runtime singletons
// (Scheduler/PlatformRuntime/PortRuntime) are additionally leaked so
// their (later-registered) destructors cannot race either.
void atexitStopEcoThread() {
    eco_app_stop();
    // If exit() was called FROM the eco thread (e.g. Eco.Process.exit),
    // joining ourselves would deadlock (musl) or fail with EDEADLK
    // (glibc); the thread is about to die with the process anyway.
    auto& s = state();
    if (s.threadValid.load() && pthread_equal(pthread_self(), s.thread)) {
        return;
    }
    eco_app_join();
}

void* ecoEmbedThread(void* /*arg*/) {
    auto& s = state();

    std::atexit(atexitStopEcoThread);

    // Mirrors eco_entry.cpp eco_main_thread (no signal handlers, no
    // GC-stats atexit — the host owns those process-level concerns).
    Elm::Allocator::instance().initialize();
    Elm::Allocator::instance().initThread();
    Eco_Kernel_register_all_gc_roots();
    initStackMapForModuleContaining(reinterpret_cast<void*>(&eco_main));
    if (__eco_init_globals) __eco_init_globals();
    Eco::Kernel::Env::init(s.argc, s.argv);
    eco_register_all_effect_managers();

    int64_t result = eco_main();

    Elm::Allocator::instance().cleanupThread();
    s.exitCode.store(static_cast<int>(result));

    // If the ready hook never fired (non-worker program, or init crashed
    // out cleanly), release the start handshake now.
    postReady();
    return nullptr;
}

}  // namespace

// ---------------------------------------------------------------------------
// C ABI
// ---------------------------------------------------------------------------

extern "C" {

int eco_app_start(int argc, char** argv, const char* flags_json) {
    auto& s = state();

    if (flags_json != nullptr) {
        // Flags decoding is Phase 5 (plans/native-ports-and-embedding.md).
        return ECO_APP_ERR_FLAGS_UNSUPPORTED;
    }
    bool expected = false;
    if (!s.started.compare_exchange_strong(expected, true)) {
        return ECO_APP_ERR_ALREADY_STARTED;
    }

    s.argc = argc;
    s.argv = argv;

    // Hold the event loop open for the app lifetime (released by
    // eco_app_stop). Taken BEFORE the thread starts so the loop can never
    // observe zero refs and exit between init and the host's first send.
    Elm::Platform::Scheduler::instance().incrementPendingAsync();

    // Ready handshake source for Platform.worker programs.
    Elm::Platform::PlatformRuntime::instance().setReadyHook(
        readyHookTrampoline, nullptr);

    pthread_attr_t attr;
    pthread_attr_init(&attr);
    pthread_attr_setstacksize(&attr, ECO_EMBED_STACK_SIZE);
    int rc = pthread_create(&s.thread, &attr, ecoEmbedThread, nullptr);
    pthread_attr_destroy(&attr);
    if (rc != 0) {
        return ECO_APP_ERR_THREAD;
    }
    s.threadValid.store(true);

    // Block until the program is initialized (ready hook) or finished
    // (thread exit posts ready too).
    {
        std::unique_lock<std::mutex> lk(s.readyMutex);
        s.readyCV.wait(lk, [&s] { return s.ready; });
    }
    return 0;
}

void eco_app_stop(void) {
    auto& s = state();
    bool expected = false;
    if (!s.stopped.compare_exchange_strong(expected, true)) {
        return;  // idempotent
    }
    auto& sched = Elm::Platform::Scheduler::instance();
    sched.requestStop();
    // Release the lifetime ref taken in eco_app_start (also wakes the
    // loop's wait predicate via the decrement's notify).
    sched.decrementPendingAsync();
}

int eco_app_join(void) {
    auto& s = state();
    std::lock_guard<std::mutex> lk(s.joinMutex);
    if (!s.threadValid.load()) {
        // Never started, or already joined: idempotent.
        return s.started.load() ? s.exitCode.load() : -1;
    }
    pthread_join(s.thread, nullptr);
    s.threadValid.store(false);
    return s.exitCode.load();
}

}  // extern "C"
