module Compiler.Elm.Version_Build exposing (userFacing)

{-| Build-time-injected user-facing version string.

Generated by CMake from `/work/version.txt` (the baseline) plus
`git describe` (for dev builds), or from `-DECO_VERSION_OVERRIDE=...`
when set (for tagged releases). The configure step writes this content
into `compiler/src/Compiler/Elm/Version_Build.elm`, overwriting the
checked-in baseline stub.

Do not edit this file directly — edits will be overwritten on the next
configure. Update `version.txt` (and the checked-in baseline in
`compiler/src/Compiler/Elm/Version_Build.elm`) when bumping the
marketing version.

@docs userFacing

-}


{-| The user-facing version string for this build.
-}
userFacing : String
userFacing =
    "0.1.1"
